module.exports=async ({db,q,scalar,denied,ok,login,workspace,owner,buyer,cook,manager,other,owner2,second,crypto})=>{
 const originalScalar=scalar, originalDenied=denied;
 const jsonArgs=args=>args.map(v=>Array.isArray(v)?JSON.stringify(v):v);
 scalar=(sql,args=[])=>originalScalar(sql,jsonArgs(args));
 denied=(sql,args,code,label)=>originalDenied(sql,jsonArgs(args),code,label);
 const id=()=>crypto.randomUUID();
 await db.exec('reset role');
 await q("update public.member_entitlements set valid_until=now()+interval '1 month' where user_id=$1",[owner]);
 await q('update public.business_members set active=true where workspace_id=$1 and user_id=$2',[workspace,buyer]);
 const supplier={name:'공동 농산',contact:'영업팀',phone:'02-000-0000',address:'서울',website:'https://example.test',active:true};
 const product={name:'국산 양파 2kg',spec:'중 / 국내산',content_quantity:2000,content_unit:'g',pack_unit:'봉',active:true};
 const saveS='select public.business_supplier_save($1,$2,$3,$4)',saveP='select public.business_supplier_product_save($1,$2,$3,$4,$5)';
 await login(cook);await denied(saveS,[workspace,id(),0,supplier],'BUSINESS_DENIED','read-only culinary staff cannot create shared suppliers');
 await login(manager);await denied(saveS,[workspace,id(),0,supplier],'BUSINESS_DENIED','financial manager does not inherit purchasing write');
 await login(buyer);let s=await scalar(saveS,[workspace,id(),0,supplier]);
 ok(s.revision===1&&s.workspace_id===workspace,'buyer creates workspace-owned supplier');
 await denied(saveS,[workspace,id(),0,{...supplier,memo:'private'}],'BUSINESS_INVALID','personal notes and unknown supplier fields cannot be silently imported');
 await denied(saveS,[workspace,id(),0,{...supplier,website:'javascript:alert(1)'}],'BUSINESS_INVALID','unsafe website scheme rejected');
 await denied(saveS,[workspace,id(),0,{...supplier,name:' '}],'BUSINESS_INVALID','empty company name rejected');
 await denied(saveS,[workspace,id(),0,{...supplier,phone:'line\nbreak'}],'BUSINESS_INVALID','control characters rejected');
 let p=await scalar(saveP,[workspace,s.id,id(),0,product]);
 ok(p.revision===1&&p.supplier_id===s.id,'pack specification belongs to selected shared supplier');
 for(const quantity of [null,0,-1,0.0000001,1e10]) await denied(saveP,[workspace,s.id,id(),0,{...product,content_quantity:quantity}],'BUSINESS_INVALID','invalid pack quantity rejected: '+quantity);
 await denied(saveP,[workspace,s.id,id(),0,{...product,content_unit:''}],'BUSINESS_INVALID','empty content unit rejected');
 await denied(saveP,[workspace,s.id,id(),0,{...product,price:999}],'BUSINESS_INVALID','unconfirmed prices cannot enter specification fields');
 await denied("update public.business_suppliers set data=$1 where id=$2",[supplier,s.id],'42501','direct supplier update blocked');
 await denied("delete from public.business_supplier_products where id=$1",[p.id],'42501','direct product deletion blocked');
 await denied('select public.business_supplier_data_valid($1,false)',[supplier],'42501','private validation helper is not exposed');
 await login(cook);ok(await scalar('select count(*)::int from public.business_suppliers where id=$1',[s.id])===1,'culinary staff with purchasing read can see shared suppliers');
 await login(other);ok(await scalar('select count(*)::int from public.business_suppliers where id=$1',[s.id])===0,'outsider cannot read supplier contact information');
 await denied(saveS,[workspace,s.id,1,supplier],'BUSINESS_DENIED','outsider cannot modify shared supplier');
 await login(owner2);const foreign=await scalar(saveS,[second,id(),0,{...supplier,name:'Other company'}]);
 await denied(saveS,[second,s.id,1,supplier],'BUSINESS_STALE','supplier ID cannot move across workspaces');
 await denied(saveP,[second,s.id,id(),0,product],'SUPPLIER_UNAVAILABLE','cross-workspace supplier product reference blocked');
 await login(cook);const recipe=await scalar('select public.business_save_record($1,$2,$3,$4,$5,0)',[workspace,id(),'recipe','양파 구매 근거',{ingredients:'',steps:'조리',notes:'',servings:4,ingredient_lines:[{name:'양파',spec:'손질',quantity:600,unit:'g'},{name:'소금',spec:'',quantity:10,unit:'g'}]}]);
 const sources=[{kind:'recipe',id:recipe.id,revision:recipe.revision,servings:30}];
 await login(buyer);const plan=await scalar('select public.business_menu_plan($1,$2,$3)',[workspace,'development',sources]);
 const key=plan.requirements.find(x=>x.name==='양파').key;
 const adjustments=plan.requirements.map(x=>({key:x.key,stock:x.name==='양파'?1000:0,incoming:0,pack_size:x.name==='양파'?2000:100,pack_unit:'봉',confirmed:true,include:true}));
 const mapping=[{key,id:p.id,revision:p.revision}], request=id(),purchase='select public.business_supplier_purchase($1,$2,$3,$4,$5,$6,$7,$8)';
 const args=(req=request,sel=s,links=mapping,adj=adjustments)=>[workspace,req,'development',sources,adj,sel.id,sel.revision,links];
 await denied(purchase,args(id(),foreign),'SUPPLIER_UNAVAILABLE','purchase cannot link supplier from another workspace');
 const another=await scalar(saveS,[workspace,id(),0,{...supplier,name:'다른 거래처'}]);
 const otherProduct=await scalar(saveP,[workspace,another.id,id(),0,product]);
 await denied(purchase,args(id(),s,[{key,id:otherProduct.id,revision:1}]),'SUPPLIER_UNAVAILABLE','product from another supplier in the same workspace cannot be selected');

 await denied(purchase,args(id(),s,[...mapping,...mapping]),'BUSINESS_INVALID','duplicate ingredient mappings rejected');
 await denied(purchase,args(id(),s,[{...mapping[0],revision:1.5}]),'BUSINESS_INVALID','fractional product revisions rejected');
 await denied(purchase,args(id(),s,[{...mapping[0],revision:2}]),'BUSINESS_STALE','stale product selection rejected');
 await denied(purchase,args(id(),s,mapping,adjustments.map(x=>x.key===key?{...x,pack_size:1000}:x)),'SUPPLIER_PACK','tampered pack quantity cannot alter supplier purchase calculation');
 await denied(purchase,args(id(),s,mapping,adjustments.map(x=>x.key===key?{...x,pack_unit:'box'}:x)),'SUPPLIER_PACK','tampered purchase unit rejected');
 await denied(purchase,args(id(),s,mapping,adjustments.map(x=>x.key===key?{...x,include:false}:x)),'SUPPLIER_UNIT','excluded ingredient cannot retain hidden product selection');
 const kg=await scalar(saveP,[workspace,s.id,id(),0,{...product,content_quantity:2,content_unit:'kg'}]);
 await denied(purchase,args(id(),s,[{key,id:kg.id,revision:1}]),'SUPPLIER_UNIT','kg pack cannot silently match gram requirement');
 let result=await scalar(purchase,args());
 const onion=result.data.lines.find(x=>x.name===product.name);
 ok(result.status==='draft'&&onion.quantity===2&&onion.unit==='봉'&&onion.price===null,'supplier purchase uses two reviewed packs and leaves price unconfirmed');
 ok(result.data.lines.some(x=>x.name==='소금'),'unlinked ingredients retain manual specification');
 ok(onion.spec.includes('양파')&&onion.spec.includes('2000'),'supplier product line preserves ingredient and pack context');
 const snap=await scalar('select to_jsonb(t) from public.business_purchase_supplier_snapshots t where request_id=$1',[request]);
 ok(snap.supplier.data.phone===supplier.phone&&snap.products[0].data.content_quantity===2000,'supplier contact and pack snapshots recorded at creation');
 ok((await scalar(purchase,args())).id===result.id,'identical supplier purchase retry returns existing request');
 await denied(purchase,args(request,s,[]),'BUSINESS_STALE','changed retry cannot overwrite supplier snapshot');
 await denied("update public.business_purchase_supplier_snapshots set products='[]' where request_id=$1",[request],'42501','purchase supplier snapshot cannot be forged');
 const originalS=s;s=await scalar(saveS,[workspace,s.id,1,{...supplier,name:'변경한 업체명',active:false}]);
 await denied(saveS,[workspace,s.id,1,supplier],'BUSINESS_STALE','supplier concurrent edits require current revision');
 await denied(saveP,[workspace,s.id,id(),0,product],'SUPPLIER_UNAVAILABLE','inactive supplier cannot receive new product');
 await denied(purchase,args(id(),s),'SUPPLIER_UNAVAILABLE','inactive supplier cannot create new purchase');
 ok((await scalar(purchase,args(request,originalS))).id===request,'successful retry remains safe after supplier is disabled');
 ok((await scalar('select supplier from public.business_purchase_supplier_snapshots where request_id=$1',[request])).data.name===supplier.name,'supplier changes do not rewrite purchase history');
 s=await scalar(saveS,[workspace,s.id,s.revision,supplier]);
 await denied(purchase,args(id(),originalS),'BUSINESS_STALE','stale supplier contact revision rejected');
 p=await scalar(saveP,[workspace,s.id,p.id,1,{...product,content_quantity:3000,active:false}]);
 ok((await scalar('select products from public.business_purchase_supplier_snapshots where request_id=$1',[request]))[0].data.content_quantity===2000,'editing pack content does not change historical quantity or product snapshot');

 await denied(purchase,args(id(),s,[{key,id:p.id,revision:p.revision}]),'SUPPLIER_UNAVAILABLE','inactive product cannot be used for new purchases');
 await login(owner2);ok(await scalar('select count(*)::int from public.business_purchase_supplier_snapshots where request_id=$1',[request])===0,'snapshot scoped to original business');
 await login(cook);await denied(purchase,args(id(),s,[]),'BUSINESS_DENIED','read-only purchasing access cannot create request');
 await db.exec('reset role');await q("update public.member_entitlements set valid_until=now()-interval '1 hour' where user_id=$1",[owner]);
 await login(buyer);await denied(saveS,[workspace,id(),0,supplier],'BUSINESS_DENIED','expired plan blocks supplier writes');
 await denied(purchase,args(id(),s,[]),'BUSINESS_DENIED','expired plan blocks supplier-linked purchase');
 await db.exec('reset role;set role anon');
 await denied(saveS,[workspace,id(),0,supplier],'42501','anonymous supplier RPC blocked');
 await denied(purchase,args(id(),s,[]),'42501','anonymous supplier purchase RPC blocked');
 await db.exec('reset role');
};
