module.exports=async ({db,q,scalar,denied,ok,login,workspace,owner,buyer,cook,manager,other,owner2,second,crypto})=>{
 // Both drivers receive JSON arrays as JSON text; node-postgres otherwise sends SQL arrays.
 const originalScalar=scalar,originalDenied=denied;
 const jsonArgs=args=>args.map(value=>Array.isArray(value)?JSON.stringify(value):value);
 scalar=(sql,args=[])=>originalScalar(sql,jsonArgs(args));
 denied=(sql,args,expected,label)=>originalDenied(sql,jsonArgs(args),expected,label);
 await db.exec('reset role');
 await q("update public.member_entitlements set valid_until=now()+interval '1 month' where user_id=$1",[owner]);
 await q('update public.business_members set active=true where workspace_id=$1 and user_id=$2',[workspace,buyer]);
 const id=()=>crypto.randomUUID();
 const data={ingredients:'derived',steps:'Cook and taste.',notes:'First batch',servings:4,ingredient_lines:[{name:'양파',spec:'손질',quantity:600,unit:'g'},{name:'당근',spec:'',quantity:200,unit:'g'}]};
 const save=(r,d)=>scalar('select public.business_save_record($1,$2,$3,$4,$5,$6)',[workspace,r?.id??id(),'recipe','Menu recipe',d,r?.revision??0]);
 const review=(r,event,stage,user)=>{return login(user).then(()=>scalar('select public.business_recipe_review($1,$2,$3,$4,$5,$6)',[workspace,r.id,r.revision,event,stage,'Tasting record']));};
 await login(cook);let r=await save(null,data);
 ok(r.data.ingredients.includes('600 g')&&!r.data.ingredients.includes('derived'),'structured ingredients determine the readable recipe');
 await denied('select public.business_data_valid_before_menu($1,$2)',['recipe',data],'42501','private pre-menu helper cannot bypass validation');
 await denied('select public.business_save_record($1,$2,$3,$4,$5,$6)',[workspace,r.id,'recipe',r.title,{...data,ingredient_lines:[{...data.ingredient_lines[0],quantity:null}]},r.revision],'BUSINESS_INVALID','missing structured quantity is rejected');
 await denied('select public.business_save_record($1,$2,$3,$4,$5,$6)',[workspace,r.id,'recipe',r.title,{ingredients:'changed without lines',steps:'Cook',notes:'',servings:4},r.revision],'MENU_STRUCTURED_REQUIRED','old client cannot silently decouple structured ingredients');
 let state=await review(r,0,'testing',cook);
 await denied('select public.business_recipe_review($1,$2,$3,$4,$5,$6)',[workspace,r.id,r.revision,0,'development','Back'],'BUSINESS_STALE','concurrent lifecycle change rejected');
 await denied('select public.business_recipe_review($1,$2,$3,$4,$5,$6)',[workspace,r.id,r.revision,state.id,'approved','Approve'],'BUSINESS_DENIED','cook cannot self-approve launch');
 state=await review(r,state.id,'approved',manager);
 ok(state.stage==='approved','management approves the tested immutable revision');
 const menuId=id();let menuData={name:'양파 메뉴',category:'식사',description:'계절 메뉴',price:9000,currency:'KRW',recipe_id:r.id,recipe_revision:1,status:'preparing'};
 const menuSave=(rev,d=menuData)=>scalar('select public.business_menu_save($1,$2,$3,$4)',[workspace,menuId,rev,d]);
 await login(buyer);await denied('select public.business_menu_save($1,$2,$3,$4)',[workspace,menuId,0,menuData],'BUSINESS_DENIED','buyer cannot change menu prices or release state');
 await login(manager);let menu=await menuSave(0);
 menu=await menuSave(menu.revision,{...menuData,status:'on_sale'});
 await denied('select public.business_menu_save($1,$2,$3,$4)',[workspace,menuId,1,menuData],'BUSINESS_STALE','menu concurrent edit rejected');
 await login(cook);const changed={...data,ingredient_lines:[{...data.ingredient_lines[0],quantity:800},data.ingredient_lines[1]]};
 r=await save(r,changed);
 ok((await scalar('select recipe_snapshot from public.business_menu_items where id=$1',[menuId])).data.ingredient_lines[0].quantity===600,'editing development recipe leaves selling menu snapshot unchanged');
 await login(manager);await denied('select public.business_menu_save($1,$2,$3,$4)',[workspace,menuId,menu.revision,{...menuData,recipe_revision:2,status:'on_sale'}],'MENU_APPROVAL_REQUIRED','unapproved new revision cannot replace released menu');
 const sources=[{kind:'menu',id:menuId,revision:menu.revision,servings:30}];
 const planSql='select public.business_menu_plan($1,$2,$3)';
 await login(buyer);const plan=await scalar(planSql,[workspace,'operations',sources]);
 ok(plan.requirements.find(x=>x.name==='양파').required===4500,'30 servings uses released 600g per 4 servings');
 await denied(planSql,[workspace,'operations',[{kind:'recipe',id:r.id,revision:r.revision,servings:30}]],'MENU_SOURCE','operations purchase cannot bypass selling menu with development recipe');
 const dev=await scalar(planSql,[workspace,'development',[{kind:'recipe',id:r.id,revision:2,servings:4}]]);
 ok(dev.requirements.find(x=>x.name==='양파').required===800,'development purchase explicitly uses selected recipe revision');
 await denied(planSql,[workspace,'development',[{kind:'recipe',id:r.id,revision:2,servings:4},{kind:'recipe',id:r.id,revision:2,servings:4}]],'BUSINESS_INVALID','duplicate source selection does not silently double purchase');
 const adjust=plan.requirements.map(x=>({key:x.key,stock:x.name==='양파'?1000:0,incoming:0,pack_size:x.name==='양파'?2000:1000,pack_unit:'봉',confirmed:true,include:true}));
 const request=id(),purchaseSql='select public.business_menu_purchase($1,$2,$3,$4,$5,$6)';
 await denied(purchaseSql,[workspace,request,'operations',sources,adjust.map(x=>({...x,confirmed:false})),'Farm'],'MENU_STOCK_CONFIRM','stock and incoming review required before purchase');
 const purchase=await scalar(purchaseSql,[workspace,request,'operations',sources,adjust,'Farm']);
 ok(purchase.data.notes.includes('v1 / 30 servings'),'exportable request notes include source revision and planned servings');
 ok(purchase.status==='draft'&&purchase.data.lines.find(x=>x.name==='양파').quantity===2,'net 3500g rounds up to two 2000g packs and remains unapproved draft');
 const basis=await scalar('select to_jsonb(b) from public.business_purchase_bases b where request_id=$1',[request]);
 ok(basis.sources[0].recipe_revision===1&&basis.adjustments.find(x=>x.key===adjust.find((a,i)=>plan.requirements[i].name==='양파').key).overage===500,'purchase basis freezes revision, servings and overage');
 ok((await scalar(purchaseSql,[workspace,request,'operations',sources,adjust,'Farm'])).id===request,'identical retry creates only one purchase');
 await denied(purchaseSql,[workspace,request,'operations',sources,adjust,'Other Farm'],'BUSINESS_STALE','changed retry cannot reuse old request');
 await denied("update public.business_purchase_bases set sources='[]' where request_id=$1",[request],'42501','member cannot forge immutable purchase basis');
 const splitAdjust=adjust.map((x,i)=>({...x,include:i===0}));
 const split=await scalar(purchaseSql,[workspace,id(),'operations',sources,splitAdjust,'Farm']);
 ok(split.data.lines.length===1,'supplier-specific selection includes only selected ingredients');
 await denied(purchaseSql,[workspace,id(),'operations',sources,adjust.map(x=>({...x,include:false})),'Farm'],'MENU_NOTHING_TO_BUY','all excluded ingredients cannot create empty request');
 await denied(purchaseSql,[workspace,id(),'operations',sources,adjust.map(x=>({...x,stock:0.0000001})),'Farm'],'MENU_STOCK_CONFIRM','more than six fractional digits cannot desync client and server');
 await denied(planSql,[workspace,'development',[{kind:'recipe',id:r.id,revision:1.1,servings:1}]],'BUSINESS_INVALID','fractional revision cannot round to an unintended source');
 await login(cook);
 const fractional=await save(null,{...data,servings:1,ingredient_lines:[{name:'허브',spec:'',quantity:0.07,unit:'g'},{name:'허브',spec:'건조',quantity:0.07,unit:'g'},{name:'허브',spec:'',quantity:0.01,unit:'kg'}]});
 await login(buyer);const fractionalSources=[{kind:'recipe',id:fractional.id,revision:1,servings:1}];
 const smallPlan=await scalar(planSql,[workspace,'development',fractionalSources]);
 ok(smallPlan.requirements.length===3,'different specification and unit stay separate');
 const small=await scalar(purchaseSql,[workspace,id(),'development',fractionalSources,smallPlan.requirements.map(x=>({key:x.key,stock:0,incoming:0,pack_size:0.01,pack_unit:'pack',confirmed:true,include:true})),'Farm']);
 ok(small.data.lines.filter(x=>x.name==='허브'&&x.quantity===7).length===2,'decimal 0.07 divided by 0.01 yields exactly seven packs');
 await login(manager);await denied('insert into public.business_menu_items(id) values($1)',[id()],'42501','direct menu writes cannot bypass approval checks');
 await login(owner2);ok(await scalar('select count(*)::int from public.business_menu_items where workspace_id=$1',[workspace])===0,'other workspace cannot read menus');
 await denied(planSql,[second,'development',[{kind:'recipe',id:r.id,revision:1,servings:1}]],'MENU_SOURCE','cross-workspace recipe reference rejected');
 await login(other);await denied(planSql,[workspace,'operations',sources],'BUSINESS_DENIED','outsider cannot derive ingredient requirements');
 await login(cook);await denied('select public.business_archive_record($1,$2,$3)',[workspace,r.id,r.revision],'MENU_ON_SALE','selling recipe cannot be archived until menu is stopped');
 await login(manager);menu=await menuSave(menu.revision,{...menuData,status:'stopped'});
 await login(buyer);await denied(planSql,[workspace,'operations',[{kind:'menu',id:menuId,revision:menu.revision,servings:30}]],'MENU_STAGE','stopped menu cannot generate new sales purchase');
 ok((await scalar('select sources from public.business_purchase_bases where request_id=$1',[request]))[0].recipe_revision===1,'stopping menu leaves historical purchase basis intact');
 await login(manager);ok(await scalar('select count(*)::int from public.business_menu_history where menu_id=$1',[menuId])===3,'menu preparation, release and stop all recorded');
 await db.exec('reset role');await q("update public.member_entitlements set valid_until=now()-interval '1 hour' where user_id=$1",[owner]);
 await login(buyer);await denied(purchaseSql,[workspace,id(),'development',[{kind:'recipe',id:r.id,revision:2,servings:4}],adjust,'Farm'],'BUSINESS_DENIED','expired business plan blocks new menu purchases');
 await db.exec('reset role;set role anon');await denied(planSql,[workspace,'operations',sources],'42501','anonymous menu plan RPC blocked');
 await db.exec('reset role');
};
