module.exports=async ({db,q,scalar,denied,ok,login,workspace,owner,buyer,cook,manager,other,owner2,second,crypto})=>{
 const os=scalar,od=denied,ja=a=>a.map(v=>Array.isArray(v) && typeof v[0]!=='string'?JSON.stringify(v):v);
 scalar=(s,a=[])=>os(s,ja(a));denied=(s,a,c,l)=>od(s,ja(a),c,l);
 const id=()=>crypto.randomUUID(),date=await scalar('select current_date::text');
 await db.exec('reset role');
 await q("update public.member_entitlements set valid_until=now()+interval '1 month' where user_id=$1",[owner]);
 await q('update public.business_members set active=true where workspace_id=$1 and user_id=$2',[workspace,buyer]);
 await login(owner);
 await scalar('select public.business_member_update($1,$2,$3,true)',[workspace,cook,['recipes.read','recipes.write','purchasing.read','menus.approve']]);
 await login(cook);
 ok(await scalar("select public.business_can($1,'menus.approve')",[workspace]),'delegated cook can approve menus');
 ok(!await scalar("select public.business_can($1,'finance.write')",[workspace]),'menu approval does not grant financial writes');
 const recipe=await scalar('select public.business_save_record($1,$2,$3,$4,$5,0)',[workspace,id(),'recipe','새 메뉴',{servings:2,ingredients:'',steps:'조리',notes:'',ingredient_lines:[{name:'양파',spec:'빠른구매',unit:'g',quantity:1000},{name:'당근',spec:'빠른구매',unit:'g',quantity:500}]}]);
 const save=(menu,revision,data)=>scalar('select public.business_menu_save($1,$2,$3,$4)',[workspace,menu,revision,data]);
 const md={name:'후보',category:'',description:'',price:null,currency:'KRW',recipe_id:recipe.id,recipe_revision:recipe.revision,status:'candidate'};
 let menu=await save(id(),0,md);ok(menu.price===null&&menu.status==='candidate','candidate can omit price and approval');
 const legacyMenu=await scalar('select to_jsonb(m) from public.business_menu_items m where id=$1',[menu.id]);
 ok(legacyMenu.status==='preparing' && typeof legacyMenu.price==='number' && legacyMenu.is_candidate && !legacyMenu.price_confirmed,'legacy clients retain supported status and non-null numeric price');
 await denied("select public.business_menu_plan($1,'launch',$2)",[workspace,[{kind:'menu',id:menu.id,revision:menu.revision,servings:1}]],'MENU_APPROVAL_REQUIRED','legacy launch purchasing cannot bypass candidate approval');
 await denied('select public.business_menu_save($1,$2,$3,$4)',[workspace,menu.id,menu.revision,{...md,status:'on_sale',price:9000}],'MENU_APPROVAL_REQUIRED','candidate cannot bypass approved launch');
 let review=await scalar("select public.business_recipe_review($1,$2,$3,0,'testing','시험 완료')",[workspace,recipe.id,recipe.revision]);
 await scalar("select public.business_recipe_review($1,$2,$3,$4,'approved','출시 승인')",[workspace,recipe.id,recipe.revision,review.id]);
 await denied('select public.business_menu_save($1,$2,$3,$4)',[workspace,menu.id,menu.revision,{...md,status:'on_sale'}],'BUSINESS_INVALID','selling menu requires an explicit price');
 menu=await save(menu.id,menu.revision,{...md,status:'on_sale',price:9000});
 await login(owner);await scalar('select public.business_member_update($1,$2,$3,true)',[workspace,cook,['recipes.read','recipes.write','purchasing.read']]);
 await login(cook);
 await denied('select public.business_menu_save($1,$2,$3,$4)',[workspace,menu.id,menu.revision,{...md,status:'candidate'}],'BUSINESS_DENIED','researcher cannot demote approved selling menu');
 ok((await save(id(),0,md)).status==='candidate','researcher can register candidate without approval rights');
 const sources=[{kind:'menu',id:menu.id,revision:menu.revision,servings:4}];
 await login(buyer);
 const preview=()=>scalar('select public.business_menu_fast_preview($1,$2,true)',[workspace,sources]);
 let view=await preview();ok(view.rows.every(r=>!r.ready),'unconfigured ingredients marked for review');
 const suppliers=[],products=[];
 for(let n=0;n<2;n++){
  const s=await scalar('select public.business_supplier_save($1,$2,0,$3)',[workspace,id(),{name:'빠른 업체 '+n,contact:'',phone:'',address:'',website:'',active:true}]);suppliers.push(s);
  products.push(await scalar('select public.business_supplier_product_save($1,$2,$3,0,$4)',[workspace,s.id,id(),{name:'상품 '+n,spec:'',content_quantity:1,content_unit:'kg',pack_unit:'봉',active:true}]));
 }
 const stock=await scalar("select public.business_stock_action($1,$2,'item',$3)",[workspace,id(),{name:'공용 채소',spec:'빠른구매',unit:'g'}]);
 await scalar("select public.business_stock_action($1,$2,'adjust',$3)",[workspace,id(),{item:stock.id,quantity:1000,reason:'실사'}]);
 const defaults=[];
 for(const [n,row] of view.rows.entries()){
  const data={ingredient:{name:row.name,spec:row.spec,unit:row.unit},supplier:suppliers[n].id,supplier_revision:1,product:products[n].id,product_revision:1,factor:1000,stock:stock.id,confirmed:true};defaults.push(data);
  await scalar('select public.business_ingredient_default_save($1,0,$2)',[workspace,data]);
 }
 view=await preview();ok(view.rows.every(r=>r.ready),'confirmed cross-unit defaults ready');
 ok(view.rows.reduce((sum,r)=>sum+r.stock,0)===1000,'same stock item allocated once across distinct ingredients');
 const create=(token,v,confirmed=true)=>scalar('select public.business_menu_batch_create($1,$2,$3,true,$4,$5,$6)',[workspace,token,sources,v.fingerprint,date,confirmed]);
 await denied('select public.business_menu_batch_create($1,$2,$3,true,$4,$5,false)',[workspace,id(),sources,view.fingerprint,date],'BUSINESS_INVALID','batch requires review confirmation');
 await scalar("select public.business_stock_action($1,$2,'adjust',$3)",[workspace,id(),{item:stock.id,quantity:1,reason:'실사 보정'}]);
 await denied('select public.business_menu_batch_create($1,$2,$3,true,$4,$5,true)',[workspace,id(),sources,view.fingerprint,date],'FAST_CHANGED','stock changes invalidate old preview');
 view=await preview();const token=id();const batch=await create(token,view);
 ok(batch.requests.length===1&&batch.reservations.length===2,'net shortages grouped with stock reservations in one transaction');
 const retry=await create(token,view);ok(JSON.stringify(retry)===JSON.stringify(batch),'uncertain retry returns original batch without duplicate requests or reservations');
 const request=await scalar('select to_jsonb(r) from public.business_records r where id=$1',[batch.requests[0].id]);
 ok(request.status==='draft'&&request.data.delivery_date===date&&request.data.lines.every(l=>l.price===null),'batch preserves approval flow, delivery and unconfirmed prices');
 const after=await preview();ok(after.rows.every(r=>r.stock===0),'second plan cannot reuse reserved stock');
 ok(after.rows.some(r=>r.open_requests>0),'open purchase overlap is visible');
 const secondBatch=await create(id(),after);ok(secondBatch.requests.length===2,'two suppliers create two distinct drafts atomically');
 await scalar('select public.business_menu_template_save($1,$2,0,$3,$4)',[workspace,id(),'월요일 점심',sources]);
 ok(await scalar('select count(*)::int from public.business_menu_templates where workspace_id=$1',[workspace])===1,'shared recurring plan stores menu revisions');
 const badDefault={...defaults[0],supplier:suppliers[1].id};
 await denied('select public.business_ingredient_default_save($1,1,$2)',[workspace,badDefault],'SUPPLIER_UNAVAILABLE','cross-supplier product rejected');
 await denied('select public.business_ingredient_default_save($1,0,$2)',[workspace,defaults[0]],'BUSINESS_STALE','concurrent default edits reject stale revision');
 await scalar('select public.business_supplier_product_save($1,$2,$3,1,$4)',[workspace,suppliers[0].id,products[0].id,{...products[0].data,content_quantity:2}]);
 const changed=await preview();ok(changed.rows.some(r=>!r.ready),'changed pack requires default reconfirmation');
 const count=await scalar('select count(*)::int from public.business_records');
 await denied('select public.business_menu_batch_create($1,$2,$3,true,$4,$5,true)',[workspace,id(),sources,changed.fingerprint,date],'FAST_MAPPING_REQUIRED','batch refuses obsolete product mapping');
 ok(await scalar('select count(*)::int from public.business_records')===count,'failed batch creates no partial requests');

 // A failure after stock reservation and possible earlier supplier writes rolls back everything.
 const tiny=await scalar('select public.business_supplier_product_save($1,$2,$3,0,$4)',[workspace,suppliers[0].id,id(),{name:'아주 작은 포장',spec:'',content_quantity:0.000001,content_unit:'g',pack_unit:'개',active:true}]);
 await scalar('select public.business_ingredient_default_save($1,1,$2)',[workspace,{...defaults[0],product:tiny.id,product_revision:1,factor:1}]);
 await scalar("select public.business_stock_action($1,$2,'adjust',$3)",[workspace,id(),{item:stock.id,quantity:10,reason:'추가 실사'}]);
 sources[0].servings=400;
 const overflow=await preview();
 const beforeEvents=await scalar('select count(*)::int from public.business_stock_events');
 await denied('select public.business_menu_batch_create($1,$2,$3,true,$4,$5,true)',[workspace,id(),sources,overflow.fingerprint,date],'BUSINESS_LIMIT','late pack overflow rolls back entire batch');
 ok(await scalar('select count(*)::int from public.business_records')===count && await scalar('select count(*)::int from public.business_stock_events')===beforeEvents,'no partial supplier drafts or stock reservations survive a late failure');
 await denied("update public.business_ingredient_defaults set factor=3",[],'42501','direct default writes denied');
 await denied("delete from public.business_menu_batches",[],'42501','batch audit cannot be directly removed');
 const revisions=await scalar('select public.business_menu_revisions($1)',[workspace]);
 ok(revisions[menu.id]===recipe.revision,'menu revision overview is scoped to business');
 sources[0].servings=4;
 await login(cook);await denied('select public.business_ingredient_default_save($1,1,$2)',[workspace,defaults[0]],'BUSINESS_DENIED','researcher cannot change purchasing defaults');
 await login(other);ok(await scalar('select count(*)::int from public.business_ingredient_defaults')===0,'outsider cannot read defaults');
 await denied('select public.business_menu_fast_preview($1,$2,true)',[workspace,sources],'BUSINESS_DENIED','outsider cannot preview another business');
 await login(owner2);await denied('select public.business_ingredient_default_save($1,0,$2)',[second,defaults[0]],'SUPPLIER_UNAVAILABLE','foreign supplier IDs rejected');
 await login(owner);await scalar('select public.business_member_update($1,$2,$3,false)',[workspace,buyer,['recipes.read','purchasing.read','purchasing.write']]);
 await login(buyer);await denied('select public.business_menu_batch_create($1,$2,$3,true,$4,$5,true)',[workspace,token,sources,view.fingerprint,date],'BUSINESS_DENIED','revoked buyer cannot replay successful batch');
 await db.exec('reset role');await db.exec('set role anon');
 await denied('select public.business_menu_fast_preview($1,$2,true)',[workspace,sources],'42501','anonymous fast preview denied');
 await db.exec('reset role');
};
