module.exports=async ({db,q,scalar,denied,ok,login,workspace,owner,buyer,cook,manager,other,owner2,second,crypto})=>{
 const os=scalar,od=denied,ja=a=>a.map(v=>Array.isArray(v)?JSON.stringify(v):v);
 scalar=(s,a=[])=>os(s,ja(a));denied=(s,a,c,l)=>od(s,ja(a),c,l);
 const id=()=>crypto.randomUUID(),rpc='select public.business_stock_action($1,$2,$3,$4)';
 const action=(kind,data,token=id(),w=workspace)=>scalar(rpc,[w,token,kind,data]);
 const no=(kind,data,code,label,token=id(),w=workspace)=>denied(rpc,[w,token,kind,data],code,label);
 const balance=async item=>(await scalar('select public.business_stock_overview($1)',[workspace])).find(x=>x.id===item.id);
 await db.exec('reset role');
 await q("update public.member_entitlements set valid_until=now()+interval '1 month' where user_id=$1",[owner]);
 await q('update public.business_members set active=true where workspace_id=$1 and user_id=$2',[workspace,buyer]);
 await login(buyer);
 ok((await scalar('select public.business_stock_overview($1)',[workspace])).length===0,'legacy received flags do not create physical inventory');
 const legacy=(await q("select id from public.business_records where workspace_id=$1 and status='received'",[workspace]))[0];
 ok((await scalar('select public.business_receiving_overview($1,$2)',[workspace,legacy.id])).legacy,'legacy receipts are explicitly identified');
 const item=await action('item',{name:'양파',spec:'손질',unit:'g'});
 ok((await action('item',{name:' 양파 ',spec:'손질',unit:'G'})).id===item.id,'normalized stock identity reuses item');
 const kg=await action('item',{name:'양파',spec:'손질',unit:'kg'});
 ok(kg.id!==item.id,'different units remain separate without inferred conversion');
 await no('item',{name:'',spec:'',unit:'g'},'BUSINESS_INVALID','empty stock name rejected');
 await no('item',{name:'Rice',spec:'',unit:'g',price:5},'BUSINESS_INVALID','stock cannot carry undeclared financial data');
 const opening={item:item.id,quantity:1000,reason:'실사 기초 재고'},token=id();
 const result=await action('adjust',opening,token);
 ok((await action('adjust',opening,token)).id===result.id&&(await balance(item)).on_hand===1000,'uncertain stock save retries are idempotent');
 await no('adjust',{...opening,quantity:1001},'BUSINESS_STALE','changed retry payload rejected',token);
 await no('adjust',{...opening,reason:''},'INVENTORY_REASON','stock changes require reason');
 for(const quantity of [null,0,0.0000001,1e10,-1001])await no('adjust',{...opening,quantity},quantity===-1001?'INVENTORY_STOCK':'BUSINESS_INVALID','invalid or negative balance adjustment rejected '+quantity);
 await denied('update public.business_stock_events set delta=500 where id=$1',[token],'42501','stock events cannot be rewritten directly');
 await denied('select public.business_stock_balance($1,$2)',[workspace,item.id],'42501','private stock aggregation is not callable');
 await denied('select * from public.business_stock_actions',[],'42501','idempotency cache is private');
 await login(cook);
 await no('adjust',opening,'BUSINESS_DENIED','culinary role cannot adjust physical stock');
 await no('item',{name:'x',spec:'',unit:'g'},'BUSINESS_DENIED','culinary role cannot register purchasing inventory');
 const reserve=await action('reserve',{item:item.id,quantity:600,reason:'점심 조리'});
 ok((await balance(item)).available===400&&(await balance(item)).on_hand===1000,'reservation reduces available stock only');
 await no('reserve',{item:item.id,quantity:401,reason:'저녁'},'INVENTORY_STOCK','second reservation cannot overbook stock');
 await action('consume',{reservation:reserve.id,revision:1,quantity:200,reason:'실제 사용'});
 let b=await balance(item);ok(b.on_hand===800&&b.reserved===400&&b.available===400,'partial consumption reduces physical and reserved quantities');
 await no('consume',{reservation:reserve.id,revision:1,quantity:100,reason:'중복'},'BUSINESS_STALE','stale reservation revision rejected');
 await no('consume',{reservation:reserve.id,revision:2,quantity:401,reason:'초과'},'INVENTORY_RESERVATION','consumption cannot exceed remaining reservation');
 await action('release',{reservation:reserve.id,revision:2,reason:'메뉴 변경'});
 b=await balance(item);ok(b.reserved===0&&b.on_hand===800,'release preserves physical stock');
 await no('release',{reservation:reserve.id,revision:3,reason:'재시도'},'INVENTORY_RESERVATION','empty reservation cannot be released twice');
 await login(manager);await no('reserve',{item:item.id,quantity:1,reason:'x'},'BUSINESS_DENIED','financial manager does not inherit cooking write');
 await login(other);ok(await scalar('select count(*)::int from public.business_stock_items')===0,'outsider cannot read inventory RLS');
 await denied('select public.business_stock_overview($1)',[workspace],'BUSINESS_DENIED','outsider cannot aggregate inventory');
 await login(owner2);await no('reserve',{item:item.id,quantity:1,reason:'x'},'BUSINESS_NOT_FOUND','cross-workspace stock selection rejected',id(),second);
 await login(buyer);
 const makePurchase=async()=>{
  const line=id();const data={supplier:'농산',buyer:'업소',phone:'',address:'',delivery_date:'',notes:'',currency:'KRW',lines:[{id:line,name:'양파 500g 봉',spec:'손질',quantity:4,unit:'봉',price:null}]};
  let r=await scalar('select public.business_save_record($1,$2,$3,$4,$5,0)',[workspace,id(),'purchase','부분 입고',data]);
  r=await scalar("select public.business_purchase_transition($1,$2,$3,'approved')",[workspace,r.id,r.revision]);
  r=await scalar("select public.business_purchase_transition($1,$2,$3,'sent')",[workspace,r.id,r.revision]);return {r,line};
 };
 let {r,line}=await makePurchase();
 const rec={request:r.id,revision:r.revision,line,item:item.id,quantity:2,factor:500,confirmed:true,reason:'검수 완료'};
 await denied("select public.business_purchase_transition($1,$2,$3,'received')",[workspace,r.id,r.revision],'INVENTORY_RECEIPT_REQUIRED','legacy transition cannot bypass line receiving');
 await denied("select public.business_purchase_transition_before_inventory($1,$2,$3,'received')",[workspace,r.id,r.revision],'42501','private transition helper cannot bypass receiving');
 await no('receive',{...rec,confirmed:false},'INVENTORY_CONVERSION','receipt requires explicit conversion confirmation');
 await no('receive',{...rec,line:id()},'BUSINESS_NOT_FOUND','receipt must reference a request line');
 await no('receive',{...rec,revision:r.revision-1},'BUSINESS_STALE','stale purchase version rejected');
 const receipt=await action('receive',rec);
 ok((await balance(item)).on_hand===1800,'two packs become explicitly confirmed 1000 grams');
 let view=await scalar('select public.business_receiving_overview($1,$2)',[workspace,r.id]);
 ok(view.status==='sent'&&view.lines[0].net===2&&view.lines[0].outstanding===2,'partial receipt does not close the request');
 await no('receive',{...rec,quantity:3},'INVENTORY_OVER_RECEIPT','cumulative receipts cannot exceed ordered quantity');
 await no('receive',{...rec,quantity:1,factor:100},'INVENTORY_CONVERSION','later receipts preserve first conversion');
 await no('receive',{...rec,quantity:1,item:kg.id},'INVENTORY_CONVERSION','later receipts preserve stock item');
 await no('close',{request:r.id,revision:r.revision,shortage_accepted:false,reason:'마감'},'INVENTORY_SHORTAGE','shortages require explicit acceptance');
 const hold=await action('reserve',{item:item.id,quantity:1700,reason:'저녁'});
 await no('return',{receipt:receipt.id,quantity:1,reason:'품질'},'INVENTORY_STOCK','returns cannot consume reserved physical stock');
 await action('release',{reservation:hold.id,revision:1,reason:'예약 취소'});
 await action('return',{receipt:receipt.id,quantity:1,reason:'품질 반품'});
 await no('return',{receipt:receipt.id,quantity:2,reason:'과다 반품'},'INVENTORY_RETURN','cumulative returns cannot exceed original receipt');
 view=await scalar('select public.business_receiving_overview($1,$2)',[workspace,r.id]);
 ok(view.lines[0].net===1&&view.lines[0].returned===1&&view.lines[0].outstanding===3,'return recalculates net receipt and shortage');
 const closed=await action('close',{request:r.id,revision:r.revision,shortage_accepted:true,reason:'잔량 별도 요청 예정'});
 ok(closed.status==='received','explicit shortage closure advances status');
 view=await scalar('select public.business_receiving_overview($1,$2)',[workspace,r.id]);
 ok(view.closure.shortage&&!view.legacy&&view.closure.reason==='잔량 별도 요청 예정','closure preserves shortage and reason snapshot');
 await no('receive',{...rec,quantity:1},'INVENTORY_PURCHASE_STATE','closed request cannot receive further replacements');
 await action('return',{receipt:receipt.id,quantity:1,reason:'마감 후 반품'});
 view=await scalar('select public.business_receiving_overview($1,$2)',[workspace,r.id]);
 ok(view.status==='received'&&view.lines[0].net===0,'post-close return is visible without silently reopening request');
 const otherPurchase=await makePurchase();
 await action('receive',{...rec,request:otherPurchase.r.id,revision:otherPurchase.r.revision,line:otherPurchase.line,quantity:1});
 const before=(await balance(item)).on_hand;
 await scalar("select public.business_purchase_transition($1,$2,$3,'cancelled')",[workspace,otherPurchase.r.id,otherPurchase.r.revision]);
 ok((await balance(item)).on_hand===before,'cancelling partial request does not silently remove received stock');
 await no('receive',{...rec,request:otherPurchase.r.id,revision:otherPurchase.r.revision,line:otherPurchase.line,quantity:1},'INVENTORY_PURCHASE_STATE','cancelled request blocks additional receipts');
 const complete=await makePurchase();
 await action('receive',{...rec,request:complete.r.id,revision:complete.r.revision,line:complete.line,quantity:4});
 await action('close',{request:complete.r.id,revision:complete.r.revision,shortage_accepted:false,reason:'전체 검수 완료'});
 ok(!(await scalar('select public.business_receiving_overview($1,$2)',[workspace,complete.r.id])).closure.shortage,'fully received request closes without shortage override');
 const hints=await scalar('select public.business_stock_purchase_hints($1,$2)',[workspace,[{name:'양파',spec:'손질',unit:'g'},{name:'양파',spec:'다름',unit:'g'},{name:'양파',spec:'손질',unit:'kg'}]]);
 ok(hints[0].item.id===item.id&&hints[1].item===null&&hints[2].item.id===kg.id,'stock hints match exact name specification and unit');
 ok(hints.every(h=>h.open_requests.every(x=>!['received','cancelled'].includes(x.status))),'duplicate hints exclude closed and cancelled requests');
 const events=await scalar('select public.business_stock_events_page($1,$2,$3,0)',[workspace,item.id,r.id]);
 ok(events.find(e=>e.id===receipt.id).returnable===0&&events.every(e=>e.item_unit==='g'),'receipt history returns unit and excludes already returned quantities');
 await denied('select public.business_stock_events_page($1,null,null,-1)',[workspace],'BUSINESS_INVALID','negative history page rejected');
 await login(other);await denied('select public.business_stock_events_page($1,null,null,0)',[workspace],'BUSINESS_DENIED','outsider cannot inspect movement history');
 await login(buyer);
 await login(cook);
 const recipe=await scalar('select public.business_save_record($1,$2,$3,$4,$5,0)',[workspace,id(),'recipe','duplicate test',{ingredients:'',steps:'cook',notes:'',servings:1,ingredient_lines:[{name:'양파',spec:'손질',quantity:500,unit:'g'}]}]);
 await login(buyer);
 const sources=[{kind:'recipe',id:recipe.id,revision:recipe.revision,servings:1}];
 const plan=await scalar('select public.business_menu_plan($1,$2,$3)',[workspace,'development',sources]);
 const adjustments=plan.requirements.map(x=>({key:x.key,stock:0,incoming:0,pack_size:500,pack_unit:'봉',confirmed:true,include:true}));
 const duplicate=await scalar('select public.business_menu_purchase($1,$2,$3,$4,$5,$6)',[workspace,id(),'development',sources,adjustments,'supplier']);
 const original=await scalar('select public.business_stock_purchase_hints($1,$2)',[workspace,plan.requirements]);
 ok(original[0].open_requests.some(x=>x.id===duplicate.id),'hints identify a real request created from the same ingredient');
 await scalar("select public.business_purchase_transition($1,$2,$3,'cancelled')",[workspace,duplicate.id,duplicate.revision]);
 const after=await scalar('select public.business_stock_purchase_hints($1,$2)',[workspace,plan.requirements]);
 ok(!after[0].open_requests.some(x=>x.id===duplicate.id),'cancelled overlapping request disappears from hints');
 await login(cook);ok((await scalar('select public.business_stock_overview($1)',[workspace])).length===2,'culinary staff can inspect purchasing stock');
 await no('return',{receipt:receipt.id,quantity:1,reason:'x'},'BUSINESS_DENIED','culinary staff cannot record supplier returns');
 await login(owner);await no('adjust',opening,'BUSINESS_STALE','another actor cannot reuse action token',token);
 await db.exec('reset role');await q("update public.member_entitlements set valid_until=now()-interval '1 hour' where user_id=$1",[owner]);
 await login(buyer);ok((await scalar('select public.business_stock_overview($1)',[workspace])).length===2,'expired membership retains nonfinancial stock read');
 await no('adjust',opening,'BUSINESS_DENIED','expired membership blocks stock mutation');
 await no('adjust',opening,'BUSINESS_DENIED','permission is rechecked even for cached successful action',token);
 await db.exec('reset role');await q('update public.business_members set active=false where workspace_id=$1 and user_id=$2',[workspace,buyer]);
 await login(buyer);await denied('select public.business_receiving_overview($1,$2)',[workspace,r.id],'BUSINESS_DENIED','revoked member cannot inspect receiving snapshots');
};
