module.exports=async ({db,q,scalar,denied,ok,login,workspace,owner,buyer,cook,manager,other,owner2,second,crypto})=>{
 const id=()=>crypto.randomUUID(), os=scalar, od=denied;
 const args=a=>a.map(v=>Array.isArray(v)?JSON.stringify(v):v);
 scalar=(s,a=[])=>os(s,args(a));denied=(s,a,c,l)=>od(s,args(a),c,l);
 await db.exec('reset role');
 await q("update public.member_entitlements set valid_until=now()+interval '1 month' where user_id=$1",[owner]);
 await q('update public.business_members set active=true where workspace_id=$1 and user_id=$2',[workspace,buyer]);
 await login(owner);
 const date=new Date().toISOString().slice(0,10), future=new Date(Date.now()+7*86400000).toISOString().slice(0,10);
 let recipe=await scalar("select public.business_save_record($1,$2,'recipe','식단 검증',$3,0)",[workspace,id(),{servings:2,ingredients:'',steps:'original cooking',notes:'',ingredient_lines:[{name:'식단 양파',spec:'meal',unit:'g',quantity:500}]}]);
 const sources=[{kind:'recipe',id:recipe.id,revision:recipe.revision,servings:10}];
 const token=id();
 const save=(mid,rev,day=date,slot='Lunch',src=sources)=>scalar("select public.business_meal_save($1,$2,$3,$4,$5,$6,$7,$8)",[workspace,mid,rev,day,slot,'Lunch set','Notes',src]);
 await login(buyer);await denied("select public.business_meal_save($1,$2,0,$3,'Lunch','Lunch','',$4)",[workspace,token,date,sources],'BUSINESS_DENIED','buyer cannot write meals');
 await login(cook);
 let meal=await save(token,0);
 ok(meal.snapshot.requirements[0].required===2500,'meal scales ingredients by dish servings');
 ok((await save(token,0)).revision===1,'lost save response retries without duplicate revision');
 await denied("select public.business_meal_save($1,$2,0,$3,'Lunch','duplicate','',$4)",[workspace,id(),date,sources],'MEAL_SLOT_EXISTS','one active meal per date and service');
 await denied("select public.business_meal_transition($1,$2,1,'confirmed')",[workspace,meal.id],'BUSINESS_DENIED','cook needs manager confirmation permission');
 await denied("update public.business_meal_plans set status='confirmed'",[],'42501','direct meal writes blocked');
 await login(owner);
 recipe=await scalar("select public.business_save_record($1,$2,'recipe','new recipe',$3,$4)",[workspace,recipe.id,{...recipe.data,ingredient_lines:[{name:'식단 양파',spec:'meal',unit:'g',quantity:999}],steps:'changed cooking'},recipe.revision]);
 meal=await scalar("select public.business_meal_transition($1,$2,1,'confirmed')",[workspace,meal.id]);
 ok(meal.snapshot.requirements[0].required===2500 && meal.snapshot.sources[0].recipe.data.steps==='original cooking','confirmation retains the reviewed immutable recipe revision');
 await denied("select public.business_meal_save($1,$2,2,$3,'Lunch','edit','',$4)",[workspace,meal.id,date,sources],'BUSINESS_FROZEN','confirmed meal cannot be edited');
 await login(cook);
 const copyId=id();
 const copy=()=>scalar('select public.business_meal_copy($1,$2,$3,$3,$4)',[workspace,copyId,date,future]);
 const copies=await copy();ok(copies.length===1 && JSON.stringify(await copy())===JSON.stringify(copies),'copy retry returns the same new drafts');
 const copied=await scalar('select to_jsonb(m) from public.business_meal_plans m where id=$1',[copies[0]]);
 ok(copied.status==='draft'&&copied.snapshot.requirements[0].required===2500,'copy retains recipe snapshots but requires fresh confirmation');
 await denied('select public.business_meal_copy($1,$2,$3,$3,$4)',[workspace,id(),date,future],'MEAL_SLOT_EXISTS','copy conflict rejects without overwriting');
 await denied('select public.business_meal_copy($1,$2,$3,$3,$3)',[workspace,id(),date],'BUSINESS_INVALID','overlapping copy blocked');
 await login(other);ok(await scalar('select count(*)::int from public.business_meal_plans')===0,'outsider cannot read meals');
 await denied("select public.business_meal_transition($1,$2,2,'cooked')",[workspace,meal.id],'BUSINESS_DENIED','outsider cannot transition meals');
 await login(owner2);
 await denied("select public.business_meal_save($1,$2,0,$3,'Lunch','Foreign','',$4)",[second,id(),date,sources],'BUSINESS_STALE','cross-business recipes blocked');
 await login(buyer);
 const purchase=[{kind:'meal',id:meal.id,revision:meal.revision,servings:1}];
 let view=await scalar('select public.business_menu_fast_preview($1,$2,false)',[workspace,purchase]);
 ok(view.rows[0].required===2500,'purchasing uses frozen meal quantities after recipe edits');
 await denied('select public.business_menu_fast_preview($1,$2,false)',[workspace,[{kind:'meal',id:copied.id,revision:copied.revision,servings:1}]],'MEAL_NOT_CONFIRMED','draft meal cannot be purchased');
 await denied("select public.business_menu_purchase($1,$2,'operations',$3,'[]','')",[workspace,id(),purchase],'MEAL_BATCH_REQUIRED','legacy purchase RPC cannot bypass meal deduplication');
 const supplier=await scalar('select public.business_supplier_save($1,$2,0,$3)',[workspace,id(),{name:'식단 업체',contact:'',phone:'',address:'',website:'',active:true}]);
 const product=await scalar('select public.business_supplier_product_save($1,$2,$3,0,$4)',[workspace,supplier.id,id(),{name:'식단 양파 1kg',spec:'',content_quantity:1000,content_unit:'g',pack_unit:'bag',active:true}]);
 const row=view.rows[0];
 await scalar('select public.business_ingredient_default_save($1,0,$2)',[workspace,{ingredient:{name:row.name,spec:row.spec,unit:row.unit},supplier:supplier.id,supplier_revision:1,product:product.id,product_revision:1,factor:1,stock:null,confirmed:true}]);
 view=await scalar('select public.business_menu_fast_preview($1,$2,false)',[workspace,purchase]);
 const batchId=id();const create=token=>scalar('select public.business_menu_batch_create($1,$2,$3,false,$4,$5,true)',[workspace,token,purchase,view.fingerprint,date]);
 const batch=await create(batchId);
 ok(batch.requests.length===1,'meal creates supplier purchase draft');
 const request=await scalar('select to_jsonb(r) from public.business_records r where id=$1',[batch.requests[0].id]);
 ok(request.status==='draft' && request.data.lines[0].quantity===3,'purchase rounds pack shortage and retains draft approval workflow');
 ok(JSON.stringify(await create(batchId))===JSON.stringify(batch),'meal batch retry is idempotent');
 await denied('select public.business_menu_batch_create($1,$2,$3,false,$4,$5,true)',[workspace,id(),purchase,view.fingerprint,date],'MEAL_PURCHASE_LINKED','second buyer batch cannot purchase the same meal twice');
 await denied('select public.business_menu_batch_before_meals($1,$2,$3,false,$4,$5,true)',[workspace,id(),purchase,view.fingerprint,date],'42501','private batch helper cannot bypass duplicate guard');
 await login(owner);
 await denied("select public.business_meal_transition($1,$2,2,'cancelled')",[workspace,meal.id],'MEAL_PURCHASE_LINKED','linked procurement cannot be silently detached by cancellation');
 await login(cook);
 const cooked=await scalar("select public.business_meal_transition($1,$2,2,'cooked')",[workspace,meal.id]);
 ok(cooked.status==='cooked','culinary staff can record completion');
 ok(await scalar('select count(*)::int from public.business_meal_history where meal_id=$1',[meal.id])===3,'all lifecycle revisions retained');
 await db.exec('reset role;set role anon');
 await denied('select public.business_meal_copy($1,$2,$3,$3,$4)',[workspace,id(),date,future],'42501','anonymous meal writes blocked');
 await db.exec('reset role');
};
