// Executes only within the isolated PostgreSQL contract harness.
module.exports=async ({db,q,scalar,denied,ok,login,crypto,fs,root,workspace,owner,buyer,cook,other})=>{
 const path=require('path'),m=n=>fs.readFileSync(path.join(root,'supabase/migrations',n),'utf8'),id=()=>crypto.randomUUID();
 await db.exec('reset role;create table if not exists public.profiles(id uuid,role text);');
 await q("insert into public.profiles values($1,'admin')",[owner]);
 await db.exec(m('0060_public_supplier_listings.sql').match(/create function public.assert_supplier_directory_admin\(\)[\s\S]*?\$\$;/)[0]);
 await db.exec(m('0065_shopping_affiliate_offers.sql'));
 await db.exec(m('0071_affiliate_catalog_management.sql'));
 await db.exec(m('0080_coupang_sale_packs.sql'));
 await db.exec(m('0081_coupang_purchase_planning.sql'));
 ok(true,'Coupang planning migrations compile with real menu, meal, inventory and affiliate schemas');
 const pack={amount:900,unit:'g',units_per_order:1,label:'봉',option:'900g 1봉'};
 const product={program:'coupang',title:'소면 900g',specification:'900g × 1봉',ingredients:['소면'],link:'https://link.coupang.com/a/PlanningTest',review_note:'Verified fixture option and web/mobile publication',mobile_allowed:true,web_allowed:true,published:true,product_verified:true,expires_at:new Date(Date.now()+86400000).toISOString(),purchase_pack:pack};
 async function admin(){await login(owner);await q("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:owner,aal:'aal2',is_anonymous:false})]);}
 const save=(data,rev=0)=>scalar('select public.admin_save_shopping_affiliate($1,$2)',[data,rev]);
 await admin();
 const offerId=await save(product);
 let offer=(await q("select * from public.find_shopping_affiliates_v2('소면','web')"))[0];
 ok(offer.purchase_pack.amount===900 && Number(offer.revision)===1,'verified packaging published with revision');
 const invalid=[{...pack,amount:0},{...pack,amount:-1},{...pack,units_per_order:1.5},{...pack,unit:'봉'},{...pack,option:''},{...pack,amount:0.0000001}];
 for(const p of invalid) await denied('select public.admin_save_shopping_affiliate($1,0)',[{...product,link:'https://link.coupang.com/a/X'+id().replaceAll('-',''),purchase_pack:p}],'AFFILIATE_PACK_INVALID','invalid sale pack rejected');
 await login(buyer);await denied('select public.admin_save_shopping_affiliate($1,0)',[product],null,'buyer cannot change affiliate packaging');
 await login(owner,true);ok((await q("select * from public.find_shopping_affiliates_v2('소면','web')")).length===0,'anonymous users cannot read published packs');
 await admin();
 await save({...product,id:offerId,web_allowed:false},1);
 ok((await q("select * from public.find_shopping_affiliates_v2('소면','web')")).length===0,'surface publication filtering preserved');
 await save({...product,id:offerId},2);
 offer=(await q("select * from public.find_shopping_affiliates_v2('소면','web')"))[0];
 // Build a real approved menu; one ingredient uses Coupang, one a supplier.
 await login(owner);
 const recipe=await scalar("select public.business_save_record($1,$2,'recipe','포장 계획', $3,0)",[workspace,id(),{servings:1,ingredients:'',steps:'조리',notes:'',ingredient_lines:[{name:'소면',spec:'',unit:'g',quantity:1200},{name:'양파',spec:'',unit:'g',quantity:500}]}]);
 let review=await scalar("select public.business_recipe_review($1,$2,$3,0,'testing','시험 완료')",[workspace,recipe.id,recipe.revision]);
 await scalar("select public.business_recipe_review($1,$2,$3,$4,'approved','출시 승인')",[workspace,recipe.id,recipe.revision,review.id]);
 const menu=await scalar('select public.business_menu_save($1,$2,0,$3)',[workspace,id(),{name:'포장 계획',category:'',description:'',price:5000,currency:'KRW',recipe_id:recipe.id,recipe_revision:recipe.revision,status:'on_sale'}]);
 const sources=[{kind:'menu',id:menu.id,revision:menu.revision,servings:1}];
 const sup=await scalar('select public.business_supplier_save($1,$2,0,$3)',[workspace,id(),{name:'공급업체',contact:'',phone:'',address:'',website:'',active:true}]);
 const prod=await scalar('select public.business_supplier_product_save($1,$2,$3,0,$4)',[workspace,sup.id,id(),{name:'양파',spec:'',content_quantity:500,content_unit:'g',pack_unit:'봉',active:true}]);
 await scalar('select public.business_ingredient_default_save($1,0,$2)',[workspace,{ingredient:{name:'양파',spec:'',unit:'g'},supplier:sup.id,supplier_revision:1,product:prod.id,product_revision:1,factor:1,stock:null,confirmed:true}]);
 const preview=()=>scalar('select public.business_menu_fast_preview($1,$2,false)',[workspace,sources]);
 let view=await preview();const key=view.rows.find(r=>r.name==='소면').key;
 const choice={offer,count:2,needed:1200,unit:'g'},choices={[key]:choice};
 const date=(await scalar('select current_date::text'));
 const call='select public.business_menu_batch_coupang($1,$2,$3,false,$4,$5,true,$6,$7)';
 const args=(token,cs=choices,v=view)=>[workspace,token,sources,v.fingerprint,date,cs,'web'];
 await login(other);await denied(call,args(id()),'BUSINESS_DENIED','outsider cannot create pack purchase batch');
 await login(buyer);
 await denied(call,args(id(),{[key]:{...choice,unit:'ml'}}),'BUSINESS_COUPANG_CHANGED','cross dimension conversion blocked');
 await denied(call,args(id(),{[key]:{...choice,needed:1}}),'BUSINESS_COUPANG_CHANGED','stale shortfall blocked');
 await denied(call,args(id(),{[key]:{...choice,offer:{...offer,revision:1}}}),'BUSINESS_COUPANG_CHANGED','old catalog revision blocked');
 await denied(call,args(id(),{'unknown':choice}),'BUSINESS_INVALID','unrelated ingredient key blocked');
 const token=id(),result=await scalar(call,args(token));
 ok(result.requests.length===2,'mixed list splits into Coupang and supplier drafts');
 ok(JSON.stringify(await scalar(call,args(token)))===JSON.stringify(result),'uncertain retry returns identical batch without duplicate requests');
 await denied(call,args(token,{[key]:{...choice,count:3}}),'BUSINESS_STALE','same token cannot change pack count');
 const records=await q('select * from public.business_records where id=any($1::uuid[])',[result.requests.map(r=>r.id)]);
 const cp=records.find(r=>r.data.supplier==='쿠팡'), supplier=records.find(r=>r.data.supplier==='공급업체');
 ok(cp.status==='draft'&&cp.data.lines[0].quantity===2&&cp.data.lines[0].unit==='봉','Coupang request remains draft in sale units');
 ok(cp.data.lines[0].coupang.needed===1200&&cp.data.lines[0].coupang.offer.purchase_pack.amount===900,'recipe need and product snapshot kept separately');
 ok(!supplier.data.lines.some(l=>l.coupang) && supplier.data.lines[0].quantity===1,'supplier procedure unchanged and no Coupang lines leak');
 await denied('select public.business_purchase_transition($1,$2,$3,\'sent\')',[workspace,cp.id,cp.revision],'BUSINESS_TRANSITION','draft cannot bypass approval');
 // Stale approval is rejected, but an unchanged approved plan can receive real packs.
 await login(owner);
 await scalar('select public.business_settings($1,$2,true)',[workspace,'Coupang contract kitchen']);
 let current=await scalar("select public.business_purchase_transition($1,$2,$3,'review')",[workspace,cp.id,cp.revision]);
 current=await scalar("select public.business_purchase_transition($1,$2,$3,'approved')",[workspace,cp.id,current.revision]);
 current=await scalar("select public.business_purchase_transition($1,$2,$3,'sent')",[workspace,cp.id,current.revision]);
 const item=await scalar("select public.business_stock_action($1,$2,'item',$3)",[workspace,id(),{name:'소면',spec:'포장 검증',unit:'g'}]);
 const receipt=await scalar("select public.business_stock_action($1,$2,'receive',$3)",[workspace,id(),{request:cp.id,revision:current.revision,line:cp.data.lines[0].id,item:item.id,quantity:2,factor:900,confirmed:true,reason:'실제 수령 확인'}]);
 const stockRows=await scalar('select public.business_stock_overview($1)',[workspace]);
 ok(Number(stockRows.find(r=>r.id===item.id).on_hand)===1800,'two ordered packs receive as 1800g without double-counting');
 const view2=await preview(),token2=id();
 const result2=await scalar(call,args(token2,choices,view2));
 const cp2=(await q("select * from public.business_records where id=$1",[result2.requests.find(r=>r.supplier==='쿠팡').id]))[0];
 await db.exec('reset role');
 ok(await scalar('select public.coupang_pack_quantity($1,\'g\')',[{...pack,amount:0.5,unit:'kg',units_per_order:2}])==='1000.0' || Number(await scalar('select public.coupang_pack_quantity($1,\'g\')',[{...pack,amount:0.5,unit:'kg',units_per_order:2}]))===1000,'inner packs multiplied exactly once');
 ok(await scalar('select public.coupang_pack_quantity($1,\'ml\')',[pack])===null,'mass-volume arithmetic rejected');
 await admin();
 const legacy={...product,id:offerId,title:'변경된 상품'};delete legacy.purchase_pack;
 await save(legacy,3);
 ok((await q("select * from public.find_shopping_affiliates_v2('소면','web')"))[0].purchase_pack===null,'old editor identity change clears stale packaging');
 await login(owner);
 await denied("select public.business_purchase_transition($1,$2,$3,'review')",[workspace,cp2.id,cp2.revision],'BUSINESS_COUPANG_CHANGED','changed catalog blocks stale request approval');

 // Search discovery against the actual workspace/supplier schema and permission function.
 await db.exec('reset role');await db.exec(m('0082_purchase_name_search.sql'));
 await login(buyer);
 const suggestions=await q("select * from public.search_purchase_names('양','web',0,$1)",[workspace]);
 ok(suggestions.some(r=>r.name==='양파'),'own supplier product can be discovered without an affiliate');
 ok(!(await q("select * from public.search_purchase_names('양','web',0)")).some(r=>r.name==='양파'),'private supplier names never enter personal discovery');
 await login(other);
 await denied("select * from public.search_purchase_names('양','web',0,$1)",[workspace],'BUSINESS_DENIED','outsider cannot enumerate workspace purchase names');
 await db.exec('reset role');
 await q("update public.business_supplier_products set data=jsonb_set(data,'{active}','false') where id=$1",[prod.id]);
 await login(buyer);
 ok(!(await q("select * from public.search_purchase_names('양파','web',0,$1)",[workspace])).some(r=>r.example_title.includes('공급업체')),'inactive supplier product excluded from purchase suggestions');
};
