// Runs in the isolated business contract database; never connects to production.
module.exports=async ({db,q,scalar,denied,ok,login,crypto,fs,root,workspace,owner,buyer,cook,other})=>{
 const path=require('path'),m=n=>fs.readFileSync(path.join(root,'supabase/migrations',n),'utf8');
 const id=()=>crypto.randomUUID();
 await db.exec(`reset role;create schema storage;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,metadata jsonb);
 alter table storage.objects enable row level security;
 create table public.kitchen_shopping_items(id uuid,owner_id uuid);`);
 await db.exec('create function public.save_supplier_purchase_request('+m('0052_supplier_purchase_requests.sql').split('create function public.save_supplier_purchase_request(')[1]);
 await db.exec(m('0059_supplier_catalog_procurement.sql'));
 await db.exec(m('0061_purchase_request_business_documents.sql'));
 await db.exec(m('0039_chef_sales.sql').split('create function public.chef_cost_per_serving(')[0]);
 // Keep has_chef_paid_access from the actual 0054 membership migration loaded by the harness.
 await db.exec(m('0048_chef_sales_totals_access.sql'));
 await db.exec(m('0076_management_lifecycle.sql'));
 await db.exec(m('0077_chef_sale_corrections.sql'));
 ok(true,'management migrations compile against actual request/catalog/sales tables');
 await q("update public.member_entitlements set valid_until=now()+interval '1 month' where user_id=$1",[owner]);
 await q("insert into public.member_entitlements values($1,'paid_monthly','active',now()+interval '1 month',now())",[owner]);
 await login(owner);
 const supplier=id();await q("insert into public.shopping_suppliers(id,owner_id,name) values($1,$2,'Draft test')",[supplier,owner]);
 await denied('delete from public.shopping_suppliers where id=$1',[supplier],'42501','legacy clients cannot erase supplier directory identity');
 const data={buyer:'Buyer',phone:'',address:'',delivery_date:'',delivery_window:'',notes:'',currency:'KRW',
  supplier:{id:supplier,name:'Draft test',contact:'',phone:'',products:''},
  lines:[{id:id(),name:'Onion',unit:'kg',spec:'',quantity:2,price:null,source_ids:[]}]};
 const save=(rid,revision,d=data,status='draft')=>scalar('select public.save_supplier_purchase_request($1,$2,$3,$4)',[rid,revision,d,status]);
 let draft=await save(id(),0);
 await denied('delete from public.supplier_purchase_requests where id=$1',[draft.id],'42501','old clients cannot hard-delete any purchase request');
 await denied('select public.delete_unused_purchase_draft($1,0)',[draft.id],'MANAGEMENT_STALE','stale deletion rejected');
 await login(other);await denied('select public.delete_unused_purchase_draft($1,$2)',[draft.id,draft.revision],'MANAGEMENT_STALE','other account cannot delete draft');
 await login(owner,true);await denied('select public.delete_unused_purchase_draft($1,$2)',[draft.id,draft.revision],'MANAGEMENT_DENIED','anonymous account cannot delete draft');
 await login(owner);
 const removed=await scalar('select public.delete_unused_purchase_draft($1,$2)',[draft.id,draft.revision]);
 ok(removed.id===draft.id,'unused draft deletes with correct revision and returns attachment snapshot');
 ok(await scalar('select public.delete_unused_purchase_draft($1,$2)',[draft.id,draft.revision])===null,'uncertain delete retry is idempotent');
 await denied('select public.save_supplier_purchase_request($1,0,$2)',[draft.id,data],'MANAGEMENT_DELETED','replayed create cannot resurrect deleted draft');
 let sent=await save(id(),0);sent=await save(sent.id,1,data,'sent');
 await denied('select public.delete_unused_purchase_draft($1,$2)',[sent.id,sent.revision],'MANAGEMENT_USED','sent request retains status history');
 let received=await save(sent.id,sent.revision,data,'accepted');received=await save(received.id,received.revision,data,'received');
 await denied('select public.delete_unused_purchase_draft($1,$2)',[received.id,received.revision],'MANAGEMENT_USED','completed request cannot be deleted');
 await db.exec('reset role');await q("update public.supplier_purchase_requests set status='draft',revision=revision+1 where id=$1",[sent.id]);
 await login(owner);await denied('select public.delete_unused_purchase_draft($1,$2)',[sent.id,received.revision+1],'MANAGEMENT_USED','legacy returned draft with past transmission still cannot be deleted');
 ok(await scalar('select count(*)::int from public.supplier_request_events where request_id=$1',[sent.id])>=4,'protected request events preserved');

 // Templates: existing batches and physical stock must remain byte-for-byte unchanged.
 const physical=()=>scalar("select md5(concat((select jsonb_agg(to_jsonb(b) order by id) from public.business_menu_batches b)::text,(select jsonb_agg(to_jsonb(s) order by id) from public.business_stock_events s)::text))");
 const before=await physical();
 let plan=await scalar('select to_jsonb(t) from public.business_menu_templates t where workspace_id=$1 limit 1',[workspace]);
 const manage=(p,action,name=null)=>scalar('select public.business_menu_template_manage($1,$2,$3,$4,$5)',[workspace,p.id,p.revision,action,name]);
 const oldPlan=plan;
 plan=await manage(plan,'rename','Managed Monday');ok(plan.name==='Managed Monday','saved plan renames without changing sources');
 await denied("select public.business_menu_template_manage($1,$2,$3,'archive')",[workspace,plan.id,oldPlan.revision],'BUSINESS_STALE','old plan revision cannot overwrite a new name');
 plan=await manage(plan,'archive');ok(plan.archived,'plan archive is reversible metadata');
 await login(cook);await denied("select public.business_menu_template_manage($1,$2,$3,'restore')",[workspace,plan.id,plan.revision],'BUSINESS_DENIED','read-only planning staff cannot restore plans');
 await login(other);ok(await scalar('select count(*)::int from public.business_management_events where workspace_id=$1',[workspace])===0,'another workspace cannot read management history');
 await login(owner);plan=await manage(plan,'restore');ok(!plan.archived,'plan restores without generating purchase orders');
 const edited=await scalar('select public.business_menu_template_save($1,$2,$3,$4,$5)',[workspace,plan.id,plan.revision,plan.name,JSON.stringify(plan.sources.map(s=>({...s,servings:6})))]);
 ok(edited.id===plan.id&&edited.revision===plan.revision+1&&edited.sources[0].servings===6,'saved plan edits its existing identity using optimistic revision');
 plan=edited;
 const copied=await scalar('select public.business_menu_template_save($1,$2,0,$3,$4)',[workspace,id(),'Plan copy',JSON.stringify(plan.sources)]);
 ok(copied.id!==plan.id&&copied.revision===1&&!copied.archived,'copy creates a distinct saved plan');
 await denied("select public.business_menu_template_manage($1,$2,$3,'rename','')",[workspace,plan.id,plan.revision],'BUSINESS_INVALID','empty plan names rejected');
 const stock=await scalar('select to_jsonb(s) from public.business_stock_items s where workspace_id=$1 limit 1',[workspace]);
 await login(cook);await denied('select public.business_stock_note($1,$2,1,$3)',[workspace,stock.id,'not allowed'],'BUSINESS_DENIED','stock notes require purchase write permission');
 await login(owner);
 const balanceBefore=await scalar('select public.business_stock_overview($1)',[workspace]);
 await q('select public.business_stock_note($1,$2,1,$3)',[workspace,stock.id,'Cold room shelf 2']);
 await denied('select public.business_stock_note($1,$2,1,$3)',[workspace,stock.id,'stale'],'BUSINESS_STALE','stale stock note cannot overwrite another user');
 const balanceAfter=await scalar('select public.business_stock_overview($1)',[workspace]);
 const clean=rows=>rows.map(({management_note,management_revision,...r})=>r);
 ok(JSON.stringify(clean(balanceBefore))===JSON.stringify(clean(balanceAfter)),'editing stock notes preserves quantity, reservations, units and identities');
 ok(await physical()===before,'plan management preserves historical batches and inventory events');
 let shared=await scalar('select to_jsonb(s) from public.business_suppliers s where workspace_id=$1 and data->>\'active\'=\'true\' limit 1',[workspace]);
 const sharedBefore=shared;
 shared=await scalar('select public.business_supplier_save($1,$2,$3,$4)',[workspace,shared.id,shared.revision,{...shared.data,active:false}]);
 ok(!shared.data.active,'shared supplier stops without deleting its identity');
 await denied('select public.business_supplier_save($1,$2,$3,$4)',[workspace,shared.id,sharedBefore.revision,sharedBefore.data],'BUSINESS_STALE','stale supplier reactivation rejected');
 shared=await scalar('select public.business_supplier_save($1,$2,$3,$4)',[workspace,shared.id,shared.revision,{...shared.data,active:true}]);
 const copiedProduct=await scalar('select public.business_supplier_product_save($1,$2,$3,0,$4)',[workspace,shared.id,id(),{name:'Spec copy',spec:'1kg',content_quantity:1,content_unit:'kg',pack_unit:'bag',active:false}]);
 ok(!copiedProduct.data.active,'copied shared specification starts inactive');
 ok(await scalar("select count(*)::int from public.business_management_events where workspace_id=$1 and kind='supplier' and action in ('deactivated','reactivated')",[workspace])===2,'supplier availability changes audited');
 await denied("delete from public.business_management_events where workspace_id=$1",[workspace],'42501','management audit is append-only for clients');

 // Active and voided personal sales use the same original price/cost snapshot.
 await db.exec('reset role');
 const sale=await scalar("insert into public.chef_sales(owner_id,recipe_title,workspace_revision,sale_date,quantity,currency,unit_price,unit_cost,markup_percent,request_key) values($1,'Soup',1,'2026-09-30',3,'KRW',5000,2000,50,$2) returning to_jsonb(chef_sales)",[owner,id()]);
 await login(owner);
 const totals=()=>scalar("select public.chef_sales_totals('2026-09-01','2026-10-01','KRW')");
 ok((await totals()).revenue===15000,'original sale contributes to totals');
 await denied('delete from public.chef_sales where id=$1',[sale.id],'42501','legacy clients cannot erase sales');
 await denied('update public.chef_sales set quantity=99 where id=$1',[sale.id],'42501','legacy direct corrections fail safely');
 await denied("select public.chef_sale_manage($1,1,'correct','','2026-09-30',4)",[sale.id],'CHEF_INVALID','correction reason required');
 await login(owner,true);await denied("select public.chef_sale_manage($1,1,'void','anonymous')",[sale.id],'CHEF_PAID_REQUIRED','anonymous identity cannot change sales');
 await login(owner);
 await q("select public.chef_sale_manage($1,1,'correct','Count corrected','2026-09-30',4)",[sale.id]);
 ok((await totals()).revenue===20000,'corrected quantity updates totals');
 await denied("select public.chef_sale_manage($1,1,'void','stale')",[sale.id],'CHEF_REVISION_CONFLICT','stale void cannot cancel a corrected sale');
 await q("select public.chef_sale_manage($1,2,'void','Entered twice')",[sale.id]);
 ok((await totals()).revenue===0,'voided sale excluded from aggregates');
 ok(await scalar('select count(*)::int from public.chef_sales where id=$1',[sale.id])===0,'old clients cannot count voided sales');
 const voided=await scalar("select public.chef_voided_sales('2026-09-01','2026-10-01','KRW')");
 ok(voided.length===1&&voided[0].unit_price===5000&&voided[0].unit_cost===2000,'voided record retains original monetary snapshot');
 await login(other);await denied("select public.chef_sale_manage($1,3,'restore','other')",[sale.id],'CHEF_PAID_REQUIRED','unpaid outsider cannot restore sale');
 await db.exec('reset role');await q("insert into public.member_entitlements values($1,'paid_monthly','active',now()+interval '1 month',now())",[other]);
 await login(other);await denied("select public.chef_sale_manage($1,3,'restore','other')",[sale.id],'CHEF_REVISION_CONFLICT','paid outsider cannot restore another account sale');
 ok(await scalar('select count(*)::int from public.chef_sale_events where sale_id=$1',[sale.id])===0,'private sale history remains private');
 await login(owner);await q("select public.chef_sale_manage($1,3,'restore','Confirmed valid')",[sale.id]);
 ok((await totals()).revenue===20000,'restoration adds sale back once');
 const events=await q('select action,before_data,after_data,reason from public.chef_sale_events where sale_id=$1 order by id',[sale.id]);
 ok(events.map(e=>e.action).join(',')==='created,corrected,voided,restored'&&events[1].before_data.quantity===3&&events[1].after_data.quantity===4,'sale correction audit records ordered before/after snapshots and reasons');
 await denied('delete from public.chef_sale_events where sale_id=$1',[sale.id],'42501','sale history cannot be deleted by clients');
 ok(await physical()===before,'sale correction and void/restore never mutate business stock');
 await db.exec('reset role');
 await require('./management_dependency_checks.cjs')({q,scalar,ok});
 await require('./owner_management_checks.cjs')({db,q,scalar,denied,ok,login,workspace,owner,buyer,other,crypto,fs,root});
 await q('delete from auth.users where id=$1',[owner]);
 ok(await scalar('select count(*)::int from public.chef_sale_events where owner_id=$1',[owner])===0,'account deletion still erases its private sale history');
 fs.writeFileSync(path.join(root,'.artifacts/management-migrations.json'),JSON.stringify({verified:true,productionWrites:0,migrations:['0076_management_lifecycle.sql','0077_chef_sale_corrections.sql','0078_owner_record_management.sql','0079_meal_purchase_link_cleanup.sql'].map(n=>({name:n,sha256:crypto.createHash('sha256').update(m(n)).digest('hex')}))},null,2));
};
