module.exports=async ({db,q,scalar,denied,ok,login,workspace,owner,buyer,other,crypto,fs,root})=>{
 const id=()=>crypto.randomUUID();
 await db.exec('reset role');
 await db.exec(fs.readFileSync(require('path').join(root,'supabase/migrations/0078_owner_record_management.sql'),'utf8'));
 await db.exec(fs.readFileSync(require('path').join(root,'supabase/migrations/0079_meal_purchase_link_cleanup.sql'),'utf8'));
 await login(owner);
 const sql='select public.owner_record_manage($1,$2,$3,$4,$5)';
 const preview=(kind,key,w=workspace,change={})=>scalar(sql,[kind,String(key),w,change,null]);
 const apply=p=>scalar(sql,[p.kind,p.id,p.workspace,p.change,p.token]);
 const action=(kind,data)=>scalar('select public.business_stock_action($1,$2,$3,$4)',[workspace,id(),kind,data]);
 const balance=async key=>(await scalar('select public.business_stock_overview($1)',[workspace])).find(x=>x.id===key);
 const item=await action('item',{name:'Unit test radish',spec:'washed',unit:'g'});
 await action('adjust',{item:item.id,quantity:2000,reason:'Opening'});
 const reservation=await action('reserve',{item:item.id,quantity:500,reason:'Lunch'});
 const p=await preview('stock_unit',item.id,workspace,{unit:'kg',factor:0.001});
 for (const change of [{unit:'kg',factor:0},{unit:'kg',factor:-1},{unit:'kg',factor:1,extra:true},{unit:'g',factor:1}]) {
  await denied(sql,['stock_unit',item.id,workspace,change,null],'MANAGEMENT_INVALID','invalid conversion is refused before a preview');
 }
 ok(p.balance.on_hand===2000&&p.after.on_hand===2&&p.after.reserved===0.5,'unit preview shows exact physical and reserved quantities');
 await login(buyer);await denied(sql,['stock_unit',item.id,workspace,p.change,p.token],'MANAGEMENT_DENIED','purchasing employee cannot perform owner-only conversion');
 await login(other);await denied(sql,['stock_unit',item.id,workspace,p.change,null],'MANAGEMENT_DENIED','outsider cannot preview stock impact');
 await login(owner,true);await denied(sql,['stock_unit',item.id,workspace,p.change,null],'MANAGEMENT_DENIED','anonymous owner claim cannot preview');
 await login(owner);
 await action('adjust',{item:item.id,quantity:1000,reason:'Concurrent delivery'});
 await denied(sql,['stock_unit',item.id,workspace,p.change,p.token],'MANAGEMENT_STALE','stock change after preview rejects entire conversion');
 ok((await balance(item.id)).on_hand===3000,'stale conversion did not mutate inventory');
 const current=await preview('stock_unit',item.id,workspace,p.change);
 const changed=await apply(current),converted=await balance(changed.replacement);
 ok(converted.unit==='kg'&&converted.on_hand===3&&converted.reserved===0.5&&converted.available===2.5,'conversion changes quantities and unit atomically');
 ok(!(await balance(item.id)),'old item identity cannot accept old-unit writes');
 ok((await apply(current)).replacement===changed.replacement,'uncertain unit conversion retry returns original result without reconverting');
 await denied('select public.business_stock_action($1,$2,$3,$4)',[workspace,id(),'adjust',{item:item.id,quantity:1000,reason:'Old screen'}],'BUSINESS_NOT_FOUND','old screen cannot adjust old identity');
 await denied('select public.business_stock_action($1,$2,$3,$4)',[workspace,id(),'consume',{reservation:reservation.id,revision:1,quantity:1,reason:'Old screen'}],'BUSINESS_STALE','old reservation revision cannot consume in the previous unit');
 const back=await apply(await preview('stock_unit',changed.replacement,workspace,{unit:'g',factor:1000}));
 ok((await balance(back.replacement)).on_hand===3000,'round trip restores exact grams');
 const blocked=await preview('stock',back.replacement);
 ok(blocked.blocked==='MANAGEMENT_RESERVED','active reservation blocks physical item erasure');
 await denied(sql,['stock',back.replacement,workspace,{},blocked.token],'MANAGEMENT_RESERVED','blocked preview cannot be forced');
 const small=await preview('stock_unit',back.replacement,workspace,{unit:'tiny',factor:0.0000000001});
 ok(small.blocked==='MANAGEMENT_PRECISION','conversion losing six-digit precision is refused');
 await action('release',{reservation:reservation.id,revision:3,reason:'Cancel lunch'});
 await apply(await preview('stock',back.replacement));
 ok(!(await balance(back.replacement)),'unreserved item and its historical movements can be erased');
 // Personal sent/completed documents are no longer restricted to unused drafts.
 const req=await scalar("select to_jsonb(r) from supplier_purchase_requests r where owner_id=$1 limit 1",[owner]);
 const reqPreview=await preview('request',req.id,null);
 await login(other);await denied(sql,['request',req.id,null,{},reqPreview.token],'MANAGEMENT_STALE','another personal owner cannot delete a request');
 await login(owner);await apply(reqPreview);await apply(reqPreview);
 ok(await scalar('select count(*)::int from supplier_purchase_requests where id=$1',[req.id])===0,'request and its status history are permanently deleted once');
 await denied('select public.save_supplier_purchase_request($1,0,$2)',[req.id,req.data],'MANAGEMENT_DELETED','deleted request replay cannot resurrect history');
 const sale=await scalar('select to_jsonb(s) from chef_sales s where owner_id=$1 limit 1',[owner]);
 const sp=await preview('sale',sale.id,null);await apply(sp);
 ok(await scalar('select count(*)::int from chef_sale_events where owner_id=$1 and sale_id=$2',[owner,sale.id])===0,'personal sale erasure removes audit payload too');
 ok((await scalar("select public.chef_sales_totals('2026-09-01','2026-10-01','KRW')")).revenue===0,'deleted sale no longer contributes to totals');
 await db.exec('reset role');
 await denied("insert into chef_sales(owner_id,recipe_title,workspace_revision,sale_date,quantity,currency,unit_price,unit_cost,markup_percent,request_key) values($1,'Replay',1,'2026-09-30',1,'KRW',100,50,50,$2)",[owner,sale.request_key],'MANAGEMENT_DELETED','deleted sale request key rejects delayed replay');
 await login(owner);
 const recipe=await scalar("select id from business_records where workspace_id=$1 and kind='recipe' limit 1",[workspace]);
 await denied(sql,['purchase',recipe,workspace,{},null],'MANAGEMENT_DENIED','forged kind cannot erase recipes through purchase management');
 // Delete a completed purchase without deducting physical inventory or losing returnability.
 const purchase=await scalar("select to_jsonb(r) from business_records r where workspace_id=$1 and kind='purchase' and status='received' and exists(select 1 from business_stock_events e where e.request_id=r.id and e.kind='receive') limit 1",[workspace]);
 const quantities=await scalar('select public.business_stock_overview($1)',[workspace]);
 const pp=await preview('purchase',purchase.id);await apply(pp);
 await login(buyer);await denied(sql,['purchase',purchase.id,workspace,{},pp.token],'MANAGEMENT_DENIED','cached success does not bypass the ownership gate');await login(owner);
 ok(JSON.stringify(await scalar('select public.business_stock_overview($1)',[workspace]))===JSON.stringify(quantities),'historical purchase deletion leaves stock balances untouched');
 ok(await scalar('select count(*)::int from business_records where id=$1',[purchase.id])===0,'completed shared purchase is deleted');
 await denied('select public.business_save_record($1,$2,$3,$4,$5,0)',[workspace,purchase.id,'purchase',purchase.title,purchase.data],'MANAGEMENT_DELETED','deleted purchase cannot be recreated by delayed save');
 const plan=await scalar('select to_jsonb(t) from business_menu_templates t where workspace_id=$1 limit 1',[workspace]);
 await apply(await preview('template',plan.id));
 ok(await scalar('select count(*)::int from business_menu_templates where id=$1',[plan.id])===0,'saved plan can be permanently removed');
 // Purchase pack counts and prices remain unchanged while physical quantities convert.
 const source=await scalar("select to_jsonb(e) from business_stock_events e where workspace_id=$1 and kind='receive' and purchase_quantity>coalesce((select sum(t.purchase_quantity) from business_stock_events t where t.receipt_id=e.id),0) limit 1",[workspace]);
 const beforeItem=await balance(source.item_id);
 const convertedReceipt=await apply(await preview('stock_unit',source.item_id,workspace,{unit:'test-unit',factor:0.5}));
 const newItem=await balance(convertedReceipt.replacement);
 ok(newItem.on_hand===beforeItem.on_hand*0.5&&newItem.reserved===beforeItem.reserved*0.5,'custom conversion supports a user-confirmed nonstandard unit');
 const receipt=await scalar('select to_jsonb(e) from business_stock_events e where id=$1',[source.id]);
 ok(receipt.purchase_quantity===source.purchase_quantity&&receipt.factor===source.factor*0.5&&receipt.delta===source.delta*0.5,'pack quantity is unchanged and receipt factor converts with the ledger');
 const overview=await scalar('select public.business_receiving_overview($1,$2)',[workspace,source.request_id]);
 ok(overview.lines.find(x=>x.id===source.line_id).mapped_item===convertedReceipt.replacement,'future receiving uses the converted item');
 if(source.factor*0.5<=newItem.available) {
  await action('return',{receipt:source.id,quantity:1,reason:'After unit change'});
  ok((await balance(convertedReceipt.replacement)).on_hand===newItem.on_hand-source.factor*0.5,'return after conversion deducts the new unit amount');
 }
 ok((await preview('stock',convertedReceipt.replacement)).blocked!==null,'stock tied to live receipts or reservations cannot be erased alone');
 const shared=await scalar('select to_jsonb(s) from business_suppliers s where workspace_id=$1 limit 1',[workspace]);
 const product=await scalar('select to_jsonb(p) from business_supplier_products p where workspace_id=$1 and supplier_id=$2 limit 1',[workspace,shared.id]);
 await apply(await preview('product',product.id));
 ok(await scalar('select count(*)::int from business_ingredient_defaults where product_id=$1',[product.id])===0,'product deletion clears default purchasing mappings');
 const supplierPreview=await preview('supplier',shared.id);
 await login(buyer);await denied(sql,['supplier',shared.id,workspace,{},supplierPreview.token],'MANAGEMENT_DENIED','staff cannot erase shared supplier catalogs');
 await login(owner);await apply(supplierPreview);
 ok(await scalar('select count(*)::int from business_supplier_products where supplier_id=$1',[shared.id])===0,'supplier erasure includes its products');
 const directory=await scalar('select to_jsonb(s) from shopping_suppliers s where owner_id=$1 limit 1',[owner]);
 const dirPreview=await preview('supplier',directory.id,null);
 await q("update shopping_suppliers set name='Concurrent edit' where id=$1",[directory.id]);
 await denied(sql,['supplier',directory.id,null,{},dirPreview.token],'MANAGEMENT_STALE','direct directory edits invalidate deletion preview');
 await apply(await preview('supplier',directory.id,null));
 await denied("insert into shopping_suppliers(id,owner_id,name) values($1,$2,'Replay')",[directory.id,owner],'MANAGEMENT_DELETED','deleted supplier cannot be recreated by a stale upsert');
 // Fixtures here are created only in the disposable database, with no external services.
 await db.exec('reset role');
 const catalog=id(),catalogProduct=id();
 await q("insert into supplier_businesses(id,owner_id,name,contact,phone,region,delivery_regions,published) values($1,$2,'Public store','Owner','01012345678','Seoul',array['Seoul'],true)",[catalog,owner]);
 await q("insert into supplier_catalog_products(id,supplier_id,name,category,subcategory,origin,sale_unit,content_quantity,content_unit,image_path) values($1,$2,'Rice','produce','grains','unknown','bag',1,'kg','owned/photo.png')",[catalogProduct,catalog]);
 await login(owner);await apply(await preview('product',catalogProduct,null));
 ok(!await scalar('select published from supplier_businesses where id=$1',[catalog]),'last publishable catalog product erasure unpublishes its business');
 const orphan=await action('item',{name:'Delete duplicate example',spec:'',unit:'g'});
 const duplicate=await action('item',{name:'Delete duplicate example',spec:'',unit:'kg'});
 const duplicatePreview=await preview('stock_unit',orphan.id,workspace,{unit:'kg',factor:0.001});
 ok(duplicatePreview.blocked==='MANAGEMENT_DUPLICATE','existing stock identity cannot be silently merged by a unit conversion');
 await denied(sql,['stock_unit',orphan.id,workspace,duplicatePreview.change,duplicatePreview.token],'MANAGEMENT_DUPLICATE','blocked duplicate conversion cannot be forced');
 ok((await balance(orphan.id)).unit==='g'&&(await balance(duplicate.id)).unit==='kg','failed conversion leaves both original items intact');
 // Completed-request and stock cleanup is explicitly two owner-confirmed operations.
 const cleanupItem=await action('item',{name:'Cleanup receipt fixture',spec:'',unit:'kg'});
 const cleanupRequest=id(),receiptId=id(),lineId=id();
 await db.exec('reset role');
 await q("insert into business_records(id,workspace_id,kind,title,data,status) values($1,$2,'purchase','Cleanup fixture',$3,'received')",[cleanupRequest,workspace,{...purchase.data,lines:[{id:lineId,name:'Rice',unit:'bag',spec:'',quantity:2,price:null}]}]);
 await q("insert into business_stock_events(id,workspace_id,item_id,kind,delta,reason,request_id,line_id,purchase_quantity,factor) values($1,$2,$3,'receive',2,'Fixture',$4,$5,2,1)",[receiptId,workspace,cleanupItem.id,cleanupRequest,lineId]);
 await q("insert into business_stock_events(id,workspace_id,item_id,kind,delta,reason,request_id,line_id,receipt_id,purchase_quantity,factor) values($1,$2,$3,'return',-1,'Fixture',$4,$5,$6,1,1)",[id(),workspace,cleanupItem.id,cleanupRequest,lineId,receiptId]);
 await login(owner);
 ok((await preview('stock',cleanupItem.id)).blocked==='MANAGEMENT_RECEIPTS','a closed request still protects against receipt-only deletion');
 await apply(await preview('purchase',cleanupRequest));
 ok((await balance(cleanupItem.id)).on_hand===1,'request erasure leaves actual net stock before explicit cleanup');
 await apply(await preview('stock',cleanupItem.id));
 ok(!(await balance(cleanupItem.id)),'explicit stock cleanup erases orphan receipts and returns without foreign-key failure');
 const batch=await scalar('select to_jsonb(b) from business_menu_batches b where workspace_id=$1 and jsonb_array_length(result->\'requests\')>0 and exists(select 1 from business_records r where r.id=(b.result->\'requests\'->0->>\'id\')::uuid) limit 1',[workspace]);
 if (!batch) throw Error('Missing preparation fixture');
 const batchRequest=batch.result.requests[0].id;
 await apply(await preview('purchase',batchRequest));
 const marked=await scalar('select result from business_menu_batches where id=$1',[batch.id]);
 ok(marked.requests.find(r=>r.id===batchRequest).deleted===true,'saved preparation result retains identity and marks erased request instead of generating it again');
 ok(marked.reservations.length===batch.result.reservations.length,'request removal does not silently cancel cooking reservations');
 await denied('select * from management_deleted_ids',[],'42501','tombstones cannot be read by clients');
 await denied('select * from management_applied_changes',[],'42501','cached mutation receipts are private');
 await db.exec('reset role');
};
