// Local-only tests, invoked by business_workspaces_contract.cjs --inventory --cleanup.
module.exports=async ({db,q,scalar,denied,ok,login,crypto,fs,root})=>{
 const path=require('path');
 await db.exec('reset role; create table public.kitchen_ingredients(quantity numeric);');
 const m=n=>fs.readFileSync(path.join(root,'supabase/migrations',n),'utf8');
 await db.exec(m('0051_shopping_assistant.sql').split('create function public.record_shopping_purchase(')[0]);
 await db.exec(m('0052_supplier_purchase_requests.sql').split('create function public.save_supplier_purchase_request(')[0]);
 await db.exec(m('0053_shopping_supplier_directory.sql'));
 await db.exec(m('0074_purchase_record_archives.sql'));
 ok(true,'archive migration compiles against actual personal tables');
 const [owner,reader,buyer,outsider]=Array.from({length:4},()=>crypto.randomUUID());
 for(const id of [owner,reader,buyer,outsider])await q('insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())',[id,id+'@example.test']);
 await q("insert into public.member_entitlements values($1,'business_monthly','active',now()+interval '1 month',now())",[owner]);
 await login(owner);
 const workspace=await scalar('select public.business_create($1,$2)',['Cleanup fixture','Owner']);
 await db.exec('reset role');
 for(const [id,permissions] of [[reader,['purchasing.read']],[buyer,['purchasing.read','purchasing.write']]])
   await q("insert into public.business_members(workspace_id,user_id,display_name,permissions,active) values($1,$2,'Staff',$3,true)",[workspace,id,permissions]);
 const purchases={};
 for(const status of ['draft','review','approved','sent','received','cancelled']){
   const id=crypto.randomUUID();purchases[status]=id;
   await q("insert into public.business_records(id,workspace_id,kind,title,status,data,updated_by) values($1,$2,'purchase',$3,$3,$4,$5)",[id,workspace,status,{supplier:'Fixture store',lines:[{name:'carrot',quantity:2,unit:'kg',price:100}]},owner]);
 }
 const personal={};
 const req=crypto.randomUUID(),sent=crypto.randomUUID();
 for(const [id,status] of [[req,'draft'],[sent,'sent']])await q('insert into public.supplier_purchase_requests(id,owner_id,status,data) values($1,$2,$3,$4)',[id,owner,status,{supplier:{name:'My store'},lines:[{name:'onion'}]}]);
 personal.request=req;
 personal.record=await scalar("insert into public.shopping_purchase_records(owner_id,request_key,request_payload,ingredient_name,quantity,unit,paid_amount,currency) values($1,$2,'{}','onion',200,'g',100,'KRW') returning id",[owner,crypto.randomUUID()]);
 personal.favorite=await scalar("insert into public.shopping_product_favorites(owner_id,ingredient_name,unit,product_name,product_url) values($1,'onion','g','onion bag','https://example.test/product') returning id",[owner]);
 personal.supplier=crypto.randomUUID();await q("insert into public.shopping_suppliers(id,owner_id,name) values($1,$2,'My store')",[personal.supplier,owner]);
 const list=(ws,kind,archived=false,offset=0,query='',before=null)=>scalar('select public.shopping_cleanup_list($1,$2,$3,$4,$5,$6)',[ws,kind,archived,before,query,offset]);
 const index=ws=>scalar('select public.shopping_cleanup_index($1)',[ws]);
 const apply=(ws,kind,rows,archive=true)=>scalar('select public.shopping_cleanup_apply($1,$2,$3,$4)',[ws,kind,rows.map(r=>({id:r.id,token:r.token})),archive]);
 const deniedApply=(ws,kind,rows,archive,code,label)=>denied('select public.shopping_cleanup_apply($1,$2,$3,$4)',[ws,kind,rows.map(r=>({id:r.id,token:r.token})),archive],code,label);
 await login(owner);
 for(const kind of Object.keys(personal)){
   const rows=await list(null,kind),row=rows.find(r=>r.id===personal[kind]);
   ok(await apply(null,kind,[row])===1,kind+' archives one selected personal record');
   ok((await index(null)).some(r=>r.id===row.id),kind+' is hidden by archive index');
   const archived=(await list(null,kind,true)).find(r=>r.id===row.id);
   ok(await apply(null,kind,[archived],false)===1,kind+' restores from archive');
 }
 await deniedApply(null,'request',[(await list(null,'request')).find(r=>r.id===sent)],true,'CLEANUP_ACTIVE','active personal request cannot be hidden');
 const record=(await list(null,'record'))[0];
 await q('update public.shopping_purchase_records set paid_amount=120 where id=$1',[record.id]);
 await deniedApply(null,'record',[record],true,'CLEANUP_STALE','changed amount invalidates preview');
 await apply(null,'record',await list(null,'record'));
 await q('update public.shopping_purchase_records set paid_amount=130 where id=$1',[record.id]);
 ok(!(await index(null)).some(r=>r.id===record.id),'changed source automatically reappears without losing its new amount');
 await login(outsider);
 ok((await list(null,'request')).length===0,'private listing never leaks another owner');
 await deniedApply(null,'request',[{id:req,token:'forged'}],true,'CLEANUP_STALE','private write cannot target another owner');
 await denied('select public.shopping_cleanup_list($1,$2)',[workspace,'business_purchase'],'CLEANUP_DENIED','outsider cannot list team archives');
 await denied('select public.shopping_cleanup_index($1)',[workspace],'CLEANUP_DENIED','outsider cannot read team archive index');
 await denied('select * from public.shopping_cleanup_source($1,$2,$3)',[owner,null,'request'],'42501','helper cannot impersonate another owner');
 await login(reader);
 const rows=await list(workspace,'business_purchase');
 ok(rows.length===6,'authorized reader sees all six lifecycle states');
 await deniedApply(workspace,'business_purchase',[rows.find(r=>r.status==='draft')],true,'CLEANUP_DENIED','read-only member cannot archive');
 await login(buyer);
 const stockSnapshot=async()=>{
   await db.exec('reset role');
   const snapshot=[];
   for(const table of ['business_stock_items','business_stock_reservations','business_stock_events','business_receiving_closures','business_stock_actions']) snapshot.push(await scalar(`select coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]'::jsonb) from public.${table} r`));
   await login(buyer);
   return JSON.stringify(snapshot);
 };
 const stockBefore=await stockSnapshot();
 const before=await scalar("select jsonb_agg(to_jsonb(r) order by id) from public.business_records r where workspace_id=$1",[workspace]);
 for(const status of ['review','approved','sent'])await deniedApply(workspace,'business_purchase',[rows.find(r=>r.status===status)],true,'CLEANUP_ACTIVE',status+' stays visible');
 await deniedApply(workspace,'business_purchase',[rows.find(r=>r.status==='draft'),rows.find(r=>r.status==='sent')],true,'CLEANUP_ACTIVE','mixed eligible/ineligible batch rolls back atomically');
 ok((await index(workspace)).length===0,'failed batch does not partially hide records');
 const eligible=rows.filter(r=>r.eligible);
 ok(await apply(workspace,'business_purchase',eligible)===3,'draft/completed/cancelled can be archived together');
 ok((await list(workspace,'business_purchase')).length===3,'active records remain in the regular list');
 await deniedApply(workspace,'business_purchase',eligible,true,'CLEANUP_STALE','replayed old preview cannot change a newer archive decision');
 ok(await scalar('select count(*)::int from public.shopping_cleanup_events where workspace_id=$1',[workspace])===3,'shared archive actor events retained');
 ok(JSON.stringify(await scalar("select jsonb_agg(to_jsonb(r) order by id) from public.business_records r where workspace_id=$1",[workspace]))===JSON.stringify(before),'archive preserves all business quantities, amounts, status, revisions and data');
 const stored=await list(workspace,'business_purchase',true);
 await login(reader);await deniedApply(workspace,'business_purchase',stored,false,'CLEANUP_DENIED','read-only member cannot restore');
 await login(buyer);ok(await apply(workspace,'business_purchase',stored,false)===3,'authorized staff restores all selected records');
 ok(await stockSnapshot()===stockBefore,'archive and restore preserve existing stock, reservations, receiving closures and stock audit events');
 await denied("update public.shopping_record_archives set archived=true where workspace_id=$1",[workspace],'42501','direct archive mutation is denied');
 await denied("delete from public.shopping_cleanup_events where workspace_id=$1",[workspace],'42501','cleanup audit history cannot be deleted by staff');
 await deniedApply(workspace,'business_purchase',[rows[0],rows[0]],true,'CLEANUP_INVALID','duplicate targets rejected');
 await db.exec('reset role');
 await q("update public.business_records set updated_at=now()-interval '100 days' where id=$1",[purchases.cancelled]);
 await login(owner);
 ok((await list(workspace,'business_purchase',false,0,'cancelled',new Date(Date.now()-90*86400000).toISOString())).length===1,'date and literal text filters select intended candidates');
 await db.exec('reset role');
 for(let n=0;n<55;n++) await q("insert into public.supplier_purchase_requests(id,owner_id,status,data) values($1,$2,'draft',$3)",[crypto.randomUUID(),owner,{supplier:{name:'paged'},lines:[]}]);
 await login(owner);
 const page1=await list(null,'request',false,0,'paged'),page2=await list(null,'request',false,50,'paged');
 ok(page1.length===51&&page2.length===5,'server paginates with one lookahead row');
 ok(page1.slice(0,50).every(a=>!page2.some(b=>a.id===b.id)),'stable pagination does not duplicate selected rows');
 await db.exec('set role anon');await denied('select public.shopping_cleanup_index(null)',[],'42501','anonymous cleanup RPC is denied');
 await db.exec('reset role');
 fs.writeFileSync(path.join(root,'.artifacts/purchase-cleanup-db.json'),JSON.stringify({verified:true,productionWrites:0},null,2));
};
