// Execute real PostgreSQL RLS and RPCs in ephemeral PGlite, never production.
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
const { PGlite } = await import(pathToFileURL(process.env.MARKETING_PGLITE_PATH).href);
const db = new PGlite();
const admin = '11111111-1111-1111-1111-111111111111';
const ordinary = '22222222-2222-2222-2222-222222222222';
await db.exec(`create role anon; create role authenticated; create role service_role;
  create schema auth; create table auth.users (id uuid primary key);
  create function auth.uid() returns uuid language sql stable as
    $$select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid$$;
  grant usage on schema auth to authenticated;
  insert into auth.users values ('${admin}'), ('${ordinary}');`);
await db.exec(await readFile(new URL('../../supabase/migrations/0027_marketing_automation.sql', import.meta.url), 'utf8'));
await db.query('insert into marketing_admins values ($1)', [admin]);
const row = (await db.query(`insert into marketing_campaigns(created_by, topic, title, description, scenes)
  values ($1, 'shopping', 'title', 'description', '["one", "two", "three"]') returning id`, [admin])).rows[0];
await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub', '${ordinary}', false);`);
assert.equal((await db.query('select * from marketing_campaigns')).rows.length, 0);
await assert.rejects(db.query('insert into marketing_admins values ($1)', [ordinary]), /permission denied/);
await assert.rejects(db.query('select schedule_marketing_campaign($1, now() + interval \'1 day\')', [row.id]), /marketing_admin_required/);
await assert.rejects(db.query('select * from claim_marketing_campaign()'), /permission denied/);
await db.exec(`select set_config('request.jwt.claim.sub', '${admin}', false);`);
assert.equal((await db.query('select * from marketing_campaigns')).rows.length, 1);
await assert.rejects(db.query('update marketing_campaigns set status = \'published\''), /permission denied/);
await assert.rejects(db.query('select schedule_marketing_campaign($1, now())', [row.id]), /invalid_schedule/);
await db.query('select schedule_marketing_campaign($1, now() + interval \'1 day\')', [row.id]);
await assert.rejects(db.query('select schedule_marketing_campaign($1, now() + interval \'1 day\')', [row.id]), /campaign_not_draft/);
await db.exec('reset role;');
assert.equal((await db.query('select * from claim_marketing_campaign()')).rows.length, 0);
await db.query(`update marketing_campaigns set scheduled_at = now() - interval '1 minute' where id = $1`, [row.id]);
assert.equal((await db.query('select * from claim_marketing_campaign()')).rows.length, 1);
assert.equal((await db.query('select * from claim_marketing_campaign()')).rows.length, 0);
await db.query(`update marketing_campaigns set claimed_at = now() - interval '1 hour' where id = $1`, [row.id]);
await db.query('select * from claim_marketing_campaign()');
assert.equal((await db.query('select status from marketing_campaigns where id = $1', [row.id])).rows[0].status, 'needs_review');
for (let i = 0; i < 5; i++) assert.equal((await db.query('select reserve_marketing_generation() as ok')).rows[0].ok, true);
assert.equal((await db.query('select reserve_marketing_generation() as ok')).rows[0].ok, false);
await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub', '${admin}', false);`);
await assert.rejects(db.query('select cancel_marketing_campaign($1)', [row.id]), /campaign_not_cancellable/);
await db.close();
console.log('Database checks passed: admin isolation, grants, schedule validation, one-time claim, uncertain upload hold, daily cap.');
